//-------body---------
{
	name:"par_body01_01_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body01.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body01_01_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body01_01_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body01_01_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body01_01_cheer1001"},]},
	]
},
{
	name:"par_body01_02_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body01.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body01_02_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body01_02_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body01_02_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body01_02_cheer1001"},]},
	]
},
{
	name:"par_body01_03_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body01.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body01_03_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body01_03_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body01_03_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body01_03_cheer1001"},]},
	]
},
{
	name:"par_body02_01_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body02.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body02_01_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body02_01_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body02_01_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body02_01_cheer1001"},]},
	]
},
{
	name:"par_body02_02_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body02.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body02_02_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body02_02_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body02_02_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body02_02_cheer1001"},]},
	]
},
{
	name:"par_body02_03_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body02.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body02_03_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body02_03_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body02_03_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body02_03_cheer1001"},]},
	]
},
{
	name:"par_body02_04_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body02.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body02_04_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body02_04_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body02_04_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body02_04_cheer1001"},]},
	]
},
{
	name:"par_body03_01_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body03.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body03_01_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body03_01_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body03_01_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body03_01_cheer1001"},]},
	]
},
{
	name:"par_body03_02_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body03.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body03_02_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body03_02_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body03_02_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body03_02_cheer1001"},]},
	]
},
{
	name:"par_body03_03_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body03.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body03_03_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body03_03_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body03_03_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body03_03_cheer1001"},]},
	]
},
{
	name:"par_body04_01_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body04.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body04_01_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body04_01_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body04_01_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body04_01_cheer1001"},]},
	]
},
{
	name:"par_body04_02_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body04.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body04_02_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body04_02_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body04_02_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body04_02_cheer1001"},]},
	]
},
{
	name:"par_body04_03_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body04.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body04_03_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body04_03_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body04_03_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body04_03_cheer1001"},]},
	]
},
{
	name:"par_body05_01_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body05.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body05_01_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body05_01_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body05_01_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body05_01_cheer1001"},]},
	]
},
{
	name:"par_body05_02_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body05.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body05_02_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body05_02_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body05_02_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body05_02_cheer1001"},]},
	]
},
{
	name:"par_body05_03_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body05.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body05_03_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body05_03_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body05_03_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body05_03_cheer1001"},]},
	]
},
{
	name:"par_body05_04_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body05.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body05_04_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body05_04_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body05_04_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body05_04_cheer1001"},]},
	]
},
{
	name:"par_body06_01_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body06.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body06_01_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body06_01_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body06_01_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body06_01_cheer1001"},]},
	]
},
{
	name:"par_body06_02_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body06.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body06_02_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body06_02_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body06_02_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body06_02_cheer1001"},]},
	]
},
{
	name:"par_body06_03_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body06.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body06_03_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body06_03_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body06_03_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body06_03_cheer1001"},]},
	]
},
{
	name:"par_body07_01_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body07.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body07_01_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body07_01_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body07_01_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body07_01_cheer1001"},]},
	]
},
{
	name:"par_body07_02_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body07.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body07_02_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body07_02_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body07_02_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body07_02_cheer1001"},]},
	]
},
{
	name:"par_body07_03_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body07.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body07_03_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body07_03_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body07_03_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body07_03_cheer1001"},]},
	]
},
{
	name:"par_body07_04_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body07.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body07_04_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body07_04_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body07_04_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body07_04_cheer1001"},]},
	]
},
{
	name:"par_body08_01_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body08.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body08_01_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body08_01_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body08_01_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body08_01_cheer1001"},]},
	]
},
{
	name:"par_body08_02_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body08.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body08_02_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body08_02_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body08_02_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body08_02_cheer1001"},]},
	]
},
{
	name:"par_body08_03_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body08.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body08_03_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body08_03_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body08_03_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body08_03_cheer1001"},]},
	]
},
{
	name:"par_body09_01_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body09.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body09_01_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body09_01_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body09_01_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body09_01_cheer1001"},]},
	]
},
{
	name:"par_body09_02_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body09.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body09_02_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body09_02_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body09_02_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body09_02_cheer1001"},]},
	]
},
{
	name:"par_body09_03_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_body09.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_body09_03_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_body09_03_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_body09_03_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_body09_03_cheer1001"},]},
	]
},
//-------leg---------
{
	name:"par_leg01_01_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_leg01.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg01_01_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_leg01_01_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_leg01_01_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg01_01_cheer1001"},]},
	]
},
{
	name:"par_leg01_02_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_leg01.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg01_02_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_leg01_02_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_leg01_02_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg01_02_cheer1001"},]},
	]
},
{
	name:"par_leg01_03_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_leg01.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg01_03_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_leg01_03_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_leg01_03_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg01_03_cheer1001"},]},
	]
},
{
	name:"par_leg02_01_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_leg02.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg02_01_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_leg02_01_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_leg02_01_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg02_01_cheer1001"},]},
	]
},
{
	name:"par_leg02_02_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_leg02.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg02_02_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_leg02_02_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_leg02_02_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg02_02_cheer1001"},]},
	]
},
{
	name:"par_leg02_03_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_leg02.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg02_03_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_leg02_03_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_leg02_03_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg02_03_cheer1001"},]},
	]
},
{
	name:"par_leg03_01_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_leg03.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg03_01_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_leg03_01_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_leg03_01_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg03_01_cheer1001"},]},
	]
},
{
	name:"par_leg03_02_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_leg03.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg03_02_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_leg03_02_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_leg03_02_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg03_02_cheer1001"},]},
	]
},
{
	name:"par_leg03_03_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_leg03.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg03_03_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_leg03_03_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_leg03_03_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg03_03_cheer1001"},]},
	]
},
{
	name:"par_leg03_04_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_leg03.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg03_04_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_leg03_04_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_leg03_04_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg03_04_cheer1001"},]},
	]
},
{
	name:"par_leg04_01_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_leg04.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg04_01_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_leg04_01_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_leg04_01_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg04_01_cheer1001"},]},
	]
},
{
	name:"par_leg04_02_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_leg04.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg04_02_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_leg04_02_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_leg04_02_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg04_02_cheer1001"},]},
	]
},
{
	name:"par_leg04_03_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_leg04.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg04_03_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_leg04_03_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_leg04_03_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg04_03_cheer1001"},]},
	]
},
{
	name:"par_leg05_01_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_leg05.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg05_01_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_leg05_01_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_leg05_01_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg05_01_cheer1001"},]},
	]
},
{
	name:"par_leg05_02_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_leg05.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg05_02_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_leg05_02_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_leg05_02_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg05_02_cheer1001"},]},
	]
},
{
	name:"par_leg05_03_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_leg05.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg05_03_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_leg05_03_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_leg05_03_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg05_03_cheer1001"},]},
	]
},
{
	name:"par_leg06_01_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_leg06.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg06_01_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_leg06_01_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_leg06_01_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg06_01_cheer1001"},]},
	]
},
{
	name:"par_leg06_02_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_leg06.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg06_02_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_leg06_02_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_leg06_02_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg06_02_cheer1001"},]},
	]
},
{
	name:"par_leg06_03_01",type:"sprite",libs:[page.genPageURL(window.imgPath+"/units/par_leg06.spl"),page.genPageURL(window.imgPath+"/units/tank.spl")],
	actions:[
		{
			name:"stay",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg06_03_stay001"},
			]
		},
		{
			name:"crashed",subani:[
				{name:"crash",weight:10,loop:1,dit_mode:0,sprite:"chr_tank_bg"},
			]
		},
		{
			name:"move",subani:[
				{name:"stay_1",weight:10,loop:1,dit_mode:4,sprite:"par_leg06_03_walk001"},
			]
		},
		{name:"attack",subani:[{name:"attack_1",weight:10,loop:0,dit_mode:7,sprite:"par_leg06_03_attack1001"},]},
		null,
		{name:"cheer",subani:[{name:"cheer_1",weight:10,loop:1,dit_mode:0,sprite:"par_leg06_03_cheer1001"},]},
	]
},
