if(window.aisEnv.defLib && window.aisEnv.defLib.shopSpecial && !window.aisEnv.defLib.shopSpecial.inited)
{
	(function()
	{
		var defLib=window.aisEnv.defLib.shopSpecial;
		var textLib=window.aisEnv.textLib;
		defLib.inited=1;
		defLib["shop_1"]={
		codeName:"shop_1",Icon:"icon_itm_token_2_32",personalTimes:-1,personalDailyTimes:-1,globalTimes:-1,
		ItemName:textLib.shopSpecialName["shop_1"],ItemDesc:textLib.shopSpecialInfo["shop_1"],
		cost:{time:0,cash:0,gem:0,storage:[{store:"Item",type:"itm_token_1",num:5},]},
		};
		defLib["shop_2"]={
		codeName:"shop_2",Icon:"icon_itm_token_3_32",personalTimes:-1,personalDailyTimes:-1,globalTimes:-1,
		ItemName:textLib.shopSpecialName["shop_2"],ItemDesc:textLib.shopSpecialInfo["shop_2"],
		cost:{time:0,cash:0,gem:0,storage:[{store:"Gold",type:"ResGold",num:4000000},{store:"Oil",type:"ResOil",num:4000000},]},
		};
		defLib["shop_3"]={
		codeName:"shop_3",Icon:"icon_itm_token_4_32",personalTimes:-1,personalDailyTimes:-1,globalTimes:-1,
		ItemName:textLib.shopSpecialName["shop_3"],ItemDesc:textLib.shopSpecialInfo["shop_3"],
		cost:{time:0,cash:0,gem:299,storage:[]},
		};
		defLib["shop_4"]={
		codeName:"shop_4",Icon:"icon_itm_token_4_32",personalTimes:-1,personalDailyTimes:-1,globalTimes:-1,
		ItemName:textLib.shopSpecialName["shop_4"],ItemDesc:textLib.shopSpecialInfo["shop_4"],
		cost:{time:0,cash:0,gem:2888,storage:[]},
		};
		defLib["shop_5"]={
		codeName:"shop_5",Icon:"icon_DiamondMine_32",personalTimes:1,personalDailyTimes:-1,globalTimes:-1,
		ItemName:textLib.shopSpecialName["shop_5"],ItemDesc:textLib.shopSpecialInfo["shop_5"],
		cost:{time:0,cash:0,gem:0,storage:[{store:"Item",type:"itm_token_1",num:30},]},
		};
		defLib["shop_6"]={
		codeName:"shop_6",Icon:"icon_res_gold128_32",personalTimes:-1,personalDailyTimes:-1,globalTimes:-1,
		ItemName:textLib.shopSpecialName["shop_6"],ItemDesc:textLib.shopSpecialInfo["shop_6"],
		cost:{time:0,cash:0,gem:0,storage:[{store:"Item",type:"itm_token_1",num:150},{store:"Item",type:"itm_token_2",num:10},]},
		};
		defLib["shop_7"]={
		codeName:"shop_7",Icon:"icon_res_oil128_32",personalTimes:-1,personalDailyTimes:-1,globalTimes:-1,
		ItemName:textLib.shopSpecialName["shop_7"],ItemDesc:textLib.shopSpecialInfo["shop_7"],
		cost:{time:0,cash:0,gem:0,storage:[{store:"Item",type:"itm_token_1",num:150},{store:"Item",type:"itm_token_2",num:10},]},
		};
		defLib["shop_8"]={
		codeName:"shop_8",Icon:"icon_res_cube128_32",personalTimes:-1,personalDailyTimes:-1,globalTimes:-1,
		ItemName:textLib.shopSpecialName["shop_8"],ItemDesc:textLib.shopSpecialInfo["shop_8"],
		cost:{time:0,cash:0,gem:0,storage:[{store:"Item",type:"itm_token_2",num:10},]},
		};
		defLib["shop_9"]={
		codeName:"shop_9",Icon:"plu_L6_08_32",personalTimes:-1,personalDailyTimes:-1,globalTimes:-1,
		ItemName:textLib.shopSpecialName["shop_9"],ItemDesc:textLib.shopSpecialInfo["shop_9"],
		cost:{time:0,cash:0,gem:0,storage:[{store:"Item",type:"itm_token_2",num:20},{store:"Item",type:"itm_token_4",num:1},]},
		};
		defLib["shop_10"]={
		codeName:"shop_10",Icon:"plu_L7_02_32",personalTimes:-1,personalDailyTimes:-1,globalTimes:-1,
		ItemName:textLib.shopSpecialName["shop_10"],ItemDesc:textLib.shopSpecialInfo["shop_10"],
		cost:{time:0,cash:0,gem:0,storage:[{store:"Item",type:"itm_token_2",num:60},{store:"Item",type:"itm_token_3",num:2},{store:"Item",type:"itm_token_4",num:7},]},
		};
		defLib["shop_11"]={
		codeName:"shop_11",Icon:"plu_L8_08_32",personalTimes:-1,personalDailyTimes:-1,globalTimes:-1,
		ItemName:textLib.shopSpecialName["shop_11"],ItemDesc:textLib.shopSpecialInfo["shop_11"],
		cost:{time:0,cash:0,gem:0,storage:[{store:"Item",type:"itm_token_2",num:60},{store:"Item",type:"itm_token_3",num:2},{store:"Item",type:"itm_token_4",num:40},]},
		};
		defLib["shop_12"]={
		codeName:"shop_12",Icon:"par_body05_04_m_32",personalTimes:-1,personalDailyTimes:-1,globalTimes:-1,
		ItemName:textLib.shopSpecialName["shop_12"],ItemDesc:textLib.shopSpecialInfo["shop_12"],
		cost:{time:0,cash:0,gem:0,storage:[{store:"Item",type:"itm_token_2",num:60},{store:"Item",type:"itm_token_3",num:2},{store:"Item",type:"itm_token_4",num:40},]},
		};
		defLib["shop_13"]={
		codeName:"shop_13",Icon:"par_body07_02_m_32",personalTimes:-1,personalDailyTimes:-1,globalTimes:-1,
		ItemName:textLib.shopSpecialName["shop_13"],ItemDesc:textLib.shopSpecialInfo["shop_13"],
		cost:{time:0,cash:0,gem:0,storage:[{store:"Item",type:"itm_token_3",num:6},{store:"Item",type:"itm_token_4",num:10},]},
		};
		defLib["shop_14"]={
		codeName:"shop_14",Icon:"par_body07_04_m_32",personalTimes:-1,personalDailyTimes:-1,globalTimes:-1,
		ItemName:textLib.shopSpecialName["shop_14"],ItemDesc:textLib.shopSpecialInfo["shop_14"],
		cost:{time:0,cash:0,gem:0,storage:[{store:"Item",type:"itm_token_2",num:50},{store:"Item",type:"itm_token_3",num:10},{store:"Item",type:"itm_token_4",num:40},]},
		};
		defLib.catalogShopSpecial=["shop_1","shop_2","shop_3","shop_4","shop_5","shop_6","shop_7","shop_8","shop_9","shop_10","shop_11","shop_12","shop_13","shop_14",];
	})();
}
