if(window.aisEnv.defLib && window.aisEnv.defLib.vipPrivilege && !window.aisEnv.defLib.vipPrivilege.inited)
{
	(function()
	{
		var defLib=window.aisEnv.defLib.vipPrivilege;
		var textLib=window.aisEnv.textLib;
		defLib.inited=1;
		defLib["VIPLevels"]=[
			{charge:0,title:"0",name:textLib.vipPrivilegeName["viplv0"]},{charge:100,title:"1",name:textLib.vipPrivilegeName["viplv1"]},{charge:5000,title:"2",name:textLib.vipPrivilegeName["viplv2"]},{charge:10000,title:"3",name:textLib.vipPrivilegeName["viplv3"]},{charge:20000,title:"4",name:textLib.vipPrivilegeName["viplv4"]},{charge:50000,title:"5",name:textLib.vipPrivilegeName["viplv5"]},{charge:100000,title:"6",name:textLib.vipPrivilegeName["viplv6"]},{charge:200000,title:"7",name:textLib.vipPrivilegeName["viplv7"]},{charge:500000,title:"8",name:textLib.vipPrivilegeName["viplv8"]},{charge:1000000,title:"9",name:textLib.vipPrivilegeName["viplv9"]},
		];
		defLib["vipWallNum"]={
		codeName:"vipWallNum",type:"buff",name:textLib.vipPrivilegeName["vipWallNum"],desc:textLib.vipPrivilegeInfo["vipWallNum"],icon:"icon_ach_destroywalls64_32",
		levels:[
			{level:0,scope:"Wall",buff:"",modifyValue:0},
			{level:1,scope:"Wall",buff:"",modifyValue:0},
			{level:2,scope:"Wall",buff:"",modifyValue:0},
			{level:3,scope:"Wall",buff:"vipWallNum5",modifyValue:5},
			{level:4,scope:"Wall",buff:"vipWallNum5",modifyValue:5},
			{level:5,scope:"Wall",buff:"vipWallNum10",modifyValue:10},
			{level:6,scope:"Wall",buff:"vipWallNum10",modifyValue:10},
			{level:7,scope:"Wall",buff:"vipWallNum15",modifyValue:15},
			{level:8,scope:"Wall",buff:"vipWallNum15",modifyValue:15},
			{level:9,scope:"Wall",buff:"vipWallNum20",modifyValue:20},
			]
		};
		defLib["vipMineNum"]={
		codeName:"vipMineNum",type:"buff",name:textLib.vipPrivilegeName["vipMineNum"],desc:textLib.vipPrivilegeInfo["vipMineNum"],icon:"icon_ach_pvpdefenses64_32",
		levels:[
			{level:0,scope:"Mine",buff:"",modifyValue:0},
			{level:1,scope:"Mine",buff:"",modifyValue:0},
			{level:2,scope:"Mine",buff:"vipMineNum1",modifyValue:1},
			{level:3,scope:"Mine",buff:"vipMineNum1",modifyValue:1},
			{level:4,scope:"Mine",buff:"vipMineNum1",modifyValue:1},
			{level:5,scope:"Mine",buff:"vipMineNum2",modifyValue:2},
			{level:6,scope:"Mine",buff:"vipMineNum2",modifyValue:2},
			{level:7,scope:"Mine",buff:"vipMineNum3",modifyValue:3},
			{level:8,scope:"Mine",buff:"vipMineNum3",modifyValue:3},
			{level:9,scope:"Mine",buff:"vipMineNum4",modifyValue:4},
			]
		};
		defLib["vipEjectorNum"]={
		codeName:"vipEjectorNum",type:"buff",name:textLib.vipPrivilegeName["vipEjectorNum"],desc:textLib.vipPrivilegeInfo["vipEjectorNum"],icon:"icon_ach_pvpdefenses64_32",
		levels:[
			{level:0,scope:"Ejector",buff:"",modifyValue:0},
			{level:1,scope:"Ejector",buff:"",modifyValue:0},
			{level:2,scope:"Ejector",buff:"",modifyValue:0},
			{level:3,scope:"Ejector",buff:"vipEjectorNum1",modifyValue:1},
			{level:4,scope:"Ejector",buff:"vipEjectorNum1",modifyValue:1},
			{level:5,scope:"Ejector",buff:"vipEjectorNum1",modifyValue:1},
			{level:6,scope:"Ejector",buff:"vipEjectorNum2",modifyValue:2},
			{level:7,scope:"Ejector",buff:"vipEjectorNum2",modifyValue:2},
			{level:8,scope:"Ejector",buff:"vipEjectorNum2",modifyValue:2},
			{level:9,scope:"Ejector",buff:"vipEjectorNum3",modifyValue:3},
			]
		};
		defLib["vipSuperbombNum"]={
		codeName:"vipSuperbombNum",type:"buff",name:textLib.vipPrivilegeName["vipSuperbombNum"],desc:textLib.vipPrivilegeInfo["vipSuperbombNum"],icon:"icon_ach_pvpdefenses64_32",
		levels:[
			{level:0,scope:"Superbomb",buff:"",modifyValue:0},
			{level:1,scope:"Superbomb",buff:"",modifyValue:0},
			{level:2,scope:"Superbomb",buff:"",modifyValue:0},
			{level:3,scope:"Superbomb",buff:"",modifyValue:0},
			{level:4,scope:"Superbomb",buff:"",modifyValue:0},
			{level:5,scope:"Superbomb",buff:"vipSuperbombNum1",modifyValue:1},
			{level:6,scope:"Superbomb",buff:"vipSuperbombNum1",modifyValue:1},
			{level:7,scope:"Superbomb",buff:"vipSuperbombNum2",modifyValue:2},
			{level:8,scope:"Superbomb",buff:"vipSuperbombNum2",modifyValue:2},
			{level:9,scope:"Superbomb",buff:"vipSuperbombNum3",modifyValue:3},
			]
		};
		defLib["vipResCrit"]={
		codeName:"vipResCrit",type:"rescrit",name:textLib.vipPrivilegeName["vipResCrit"],desc:textLib.vipPrivilegeInfo["vipResCrit"],icon:"icon_res_all64_32",
		levels:[
			{level:0,scope:"Building",modifyValue:20,modifyValueEx:0},
			{level:1,scope:"Building",modifyValue:20,modifyValueEx:5},
			{level:2,scope:"Building",modifyValue:20,modifyValueEx:7},
			{level:3,scope:"Building",modifyValue:20,modifyValueEx:9},
			{level:4,scope:"Building",modifyValue:20,modifyValueEx:11},
			{level:5,scope:"Building",modifyValue:20,modifyValueEx:13},
			{level:6,scope:"Building",modifyValue:20,modifyValueEx:15},
			{level:7,scope:"Building",modifyValue:20,modifyValueEx:17},
			{level:8,scope:"Building",modifyValue:20,modifyValueEx:19},
			{level:9,scope:"Building",modifyValue:20,modifyValueEx:20},
			]
		};
		defLib["vipBattleWaitTime"]={
		codeName:"vipBattleWaitTime",type:"btWaitTime",name:textLib.vipPrivilegeName["vipBattleWaitTime"],desc:textLib.vipPrivilegeInfo["vipBattleWaitTime"],icon:"icon_ach_npcstars64_32",
		levels:[
			{level:0,scope:"",modifyValue:0,modifyValueEx:0},
			{level:1,scope:"",modifyValue:30,modifyValueEx:0},
			{level:2,scope:"",modifyValue:30,modifyValueEx:0},
			{level:3,scope:"",modifyValue:30,modifyValueEx:0},
			{level:4,scope:"",modifyValue:30,modifyValueEx:0},
			{level:5,scope:"",modifyValue:45,modifyValueEx:0},
			{level:6,scope:"",modifyValue:45,modifyValueEx:0},
			{level:7,scope:"",modifyValue:45,modifyValueEx:0},
			{level:8,scope:"",modifyValue:45,modifyValueEx:0},
			{level:9,scope:"",modifyValue:60,modifyValueEx:0},
			]
		};
		defLib["vipLimitedSalesGold"]={
		codeName:"vipLimitedSalesGold",type:"limitedSalesRes",name:textLib.vipPrivilegeName["vipLimitedSalesGold"],desc:textLib.vipPrivilegeInfo["vipLimitedSalesGold"],icon:"icon_res_gold64_32",
		levels:[
			{level:0,scope:"Gold",modifyValue:50,modifyValueEx:0},
			{level:1,scope:"Gold",modifyValue:50,modifyValueEx:0},
			{level:2,scope:"Gold",modifyValue:50,modifyValueEx:500000},
			{level:3,scope:"Gold",modifyValue:50,modifyValueEx:600000},
			{level:4,scope:"Gold",modifyValue:50,modifyValueEx:700000},
			{level:5,scope:"Gold",modifyValue:50,modifyValueEx:800000},
			{level:6,scope:"Gold",modifyValue:50,modifyValueEx:1000000},
			{level:7,scope:"Gold",modifyValue:50,modifyValueEx:1300000},
			{level:8,scope:"Gold",modifyValue:50,modifyValueEx:1600000},
			{level:9,scope:"Gold",modifyValue:50,modifyValueEx:2000000},
			]
		};
		defLib["vipLimitedSalesElixir"]={
		codeName:"vipLimitedSalesElixir",type:"limitedSalesRes",name:textLib.vipPrivilegeName["vipLimitedSalesElixir"],desc:textLib.vipPrivilegeInfo["vipLimitedSalesElixir"],icon:"icon_res_oil64_32",
		levels:[
			{level:0,scope:"Oil",modifyValue:50,modifyValueEx:0},
			{level:1,scope:"Oil",modifyValue:50,modifyValueEx:0},
			{level:2,scope:"Oil",modifyValue:50,modifyValueEx:500000},
			{level:3,scope:"Oil",modifyValue:50,modifyValueEx:600000},
			{level:4,scope:"Oil",modifyValue:50,modifyValueEx:700000},
			{level:5,scope:"Oil",modifyValue:50,modifyValueEx:800000},
			{level:6,scope:"Oil",modifyValue:50,modifyValueEx:1000000},
			{level:7,scope:"Oil",modifyValue:50,modifyValueEx:1300000},
			{level:8,scope:"Oil",modifyValue:50,modifyValueEx:1600000},
			{level:9,scope:"Oil",modifyValue:50,modifyValueEx:2000000},
			]
		};
		defLib["vipRequestUnitsWaitTime"]={
		codeName:"vipRequestUnitsWaitTime",type:"reqUnitsTime",name:textLib.vipPrivilegeName["vipRequestUnitsWaitTime"],desc:textLib.vipPrivilegeInfo["vipRequestUnitsWaitTime"],icon:"icon_ach_npcstars64_32",
		levels:[
			{level:0,scope:"",modifyValue:0,modifyValueEx:0},
			{level:1,scope:"",modifyValue:0,modifyValueEx:0},
			{level:2,scope:"",modifyValue:0,modifyValueEx:0},
			{level:3,scope:"",modifyValue:3,modifyValueEx:0},
			{level:4,scope:"",modifyValue:3,modifyValueEx:0},
			{level:5,scope:"",modifyValue:5,modifyValueEx:0},
			{level:6,scope:"",modifyValue:5,modifyValueEx:0},
			{level:7,scope:"",modifyValue:8,modifyValueEx:0},
			{level:8,scope:"",modifyValue:8,modifyValueEx:0},
			{level:9,scope:"",modifyValue:10,modifyValueEx:0},
			]
		};
		defLib["vipTrainTimeDiscount"]={
		codeName:"vipTrainTimeDiscount",type:"time2GemDiscount",name:textLib.vipPrivilegeName["vipTrainTimeDiscount"],desc:textLib.vipPrivilegeInfo["vipTrainTimeDiscount"],icon:"icon_cap_spd64_32",
		levels:[
			{level:0,scope:"",modifyValue:100,modifyValueEx:0},
			{level:1,scope:"",modifyValue:100,modifyValueEx:0},
			{level:2,scope:"",modifyValue:100,modifyValueEx:0},
			{level:3,scope:"",modifyValue:100,modifyValueEx:0},
			{level:4,scope:"",modifyValue:100,modifyValueEx:0},
			{level:5,scope:"",modifyValue:90,modifyValueEx:0},
			{level:6,scope:"",modifyValue:85,modifyValueEx:0},
			{level:7,scope:"",modifyValue:80,modifyValueEx:0},
			{level:8,scope:"",modifyValue:75,modifyValueEx:0},
			{level:9,scope:"",modifyValue:70,modifyValueEx:0},
			]
		};
		defLib["vipBLDTimeDiscount"]={
		codeName:"vipBLDTimeDiscount",type:"time2GemDiscount",name:textLib.vipPrivilegeName["vipBLDTimeDiscount"],desc:textLib.vipPrivilegeInfo["vipBLDTimeDiscount"],icon:"icon_cap_spd64_32",
		levels:[
			{level:0,scope:"",modifyValue:100,modifyValueEx:0},
			{level:1,scope:"",modifyValue:100,modifyValueEx:0},
			{level:2,scope:"",modifyValue:95,modifyValueEx:0},
			{level:3,scope:"",modifyValue:92,modifyValueEx:0},
			{level:4,scope:"",modifyValue:89,modifyValueEx:0},
			{level:5,scope:"",modifyValue:86,modifyValueEx:0},
			{level:6,scope:"",modifyValue:83,modifyValueEx:0},
			{level:7,scope:"",modifyValue:80,modifyValueEx:0},
			{level:8,scope:"",modifyValue:75,modifyValueEx:0},
			{level:9,scope:"",modifyValue:70,modifyValueEx:0},
			]
		};
		defLib["vipDiamonBoost"]={
		codeName:"vipDiamonBoost",type:"buffDiamon",name:textLib.vipPrivilegeName["vipDiamonBoost"],desc:textLib.vipPrivilegeInfo["vipDiamonBoost"],icon:"icon_res_gem64_32",
		levels:[
			{level:0,scope:"DiamondMine",buff:"",modifyValue:0,modifyValueEx:7},
			{level:1,scope:"DiamondMine",buff:"vipGemRush30",modifyValue:30,modifyValueEx:7},
			{level:2,scope:"DiamondMine",buff:"vipGemRush35",modifyValue:35,modifyValueEx:7},
			{level:3,scope:"DiamondMine",buff:"vipGemRush40",modifyValue:40,modifyValueEx:7},
			{level:4,scope:"DiamondMine",buff:"vipGemRush45",modifyValue:45,modifyValueEx:7},
			{level:5,scope:"DiamondMine",buff:"vipGemRush50",modifyValue:50,modifyValueEx:7},
			{level:6,scope:"DiamondMine",buff:"vipGemRush60",modifyValue:60,modifyValueEx:7},
			{level:7,scope:"DiamondMine",buff:"vipGemRush70",modifyValue:70,modifyValueEx:7},
			{level:8,scope:"DiamondMine",buff:"vipGemRush80",modifyValue:80,modifyValueEx:7},
			{level:9,scope:"DiamondMine",buff:"vipGemRush90",modifyValue:90,modifyValueEx:7},
			]
		};

		defLib=window.aisEnv.defLib.buff;
		defLib["vipWallNum5"]={
		 codeName:"vipWallNum5",
		 icon:"",durTime:172800000,
		 cost:{cash:0,gem:0,storage:[]},
		 shareName:"vipWallNum5",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"NumCapWall",add:5},
		  {scope:"City",name:"MaxCapWall",add:5},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipWallNum5"]);
		defLib["vipWallNum10"]={
		 codeName:"vipWallNum10",
		 icon:"",durTime:172800000,
		 cost:{cash:0,gem:0,storage:[]},
		 shareName:"vipWallNum10",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"NumCapWall",add:10},
		  {scope:"City",name:"MaxCapWall",add:10},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipWallNum10"]);
		defLib["vipWallNum15"]={
		 codeName:"vipWallNum15",
		 icon:"",durTime:172800000,
		 cost:{cash:0,gem:0,storage:[]},
		 shareName:"vipWallNum15",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"NumCapWall",add:15},
		  {scope:"City",name:"MaxCapWall",add:15},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipWallNum15"]);
		defLib["vipWallNum20"]={
		 codeName:"vipWallNum20",
		 icon:"",durTime:172800000,
		 cost:{cash:0,gem:0,storage:[]},
		 shareName:"vipWallNum20",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"NumCapWall",add:20},
		  {scope:"City",name:"MaxCapWall",add:20},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipWallNum20"]);
		defLib["vipMineNum1"]={
		 codeName:"vipMineNum1",
		 icon:"",durTime:172800000,
		 cost:{cash:0,gem:0,storage:[]},
		 shareName:"vipMineNum1",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"NumCapMine",add:1},
		  {scope:"City",name:"MaxCapMine",add:1},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipMineNum1"]);
		defLib["vipMineNum2"]={
		 codeName:"vipMineNum2",
		 icon:"",durTime:172800000,
		 cost:{cash:0,gem:0,storage:[]},
		 shareName:"vipMineNum2",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"NumCapMine",add:2},
		  {scope:"City",name:"MaxCapMine",add:2},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipMineNum2"]);
		defLib["vipMineNum3"]={
		 codeName:"vipMineNum3",
		 icon:"",durTime:172800000,
		 cost:{cash:0,gem:0,storage:[]},
		 shareName:"vipMineNum3",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"NumCapMine",add:3},
		  {scope:"City",name:"MaxCapMine",add:3},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipMineNum3"]);
		defLib["vipMineNum4"]={
		 codeName:"vipMineNum4",
		 icon:"",durTime:172800000,
		 cost:{cash:0,gem:0,storage:[]},
		 shareName:"vipMineNum4",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"NumCapMine",add:4},
		  {scope:"City",name:"MaxCapMine",add:4},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipMineNum4"]);
		defLib["vipEjectorNum1"]={
		 codeName:"vipEjectorNum1",
		 icon:"",durTime:172800000,
		 cost:{cash:0,gem:0,storage:[]},
		 shareName:"vipEjectorNum1",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"NumCapEjector",add:1},
		  {scope:"City",name:"MaxCapEjector",add:1},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipEjectorNum1"]);
		defLib["vipEjectorNum2"]={
		 codeName:"vipEjectorNum2",
		 icon:"",durTime:172800000,
		 cost:{cash:0,gem:0,storage:[]},
		 shareName:"vipEjectorNum2",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"NumCapEjector",add:2},
		  {scope:"City",name:"MaxCapEjector",add:2},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipEjectorNum2"]);
		defLib["vipEjectorNum3"]={
		 codeName:"vipEjectorNum3",
		 icon:"",durTime:172800000,
		 cost:{cash:0,gem:0,storage:[]},
		 shareName:"vipEjectorNum3",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"NumCapEjector",add:3},
		  {scope:"City",name:"MaxCapEjector",add:3},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipEjectorNum3"]);
		defLib["vipSuperbombNum1"]={
		 codeName:"vipSuperbombNum1",
		 icon:"",durTime:172800000,
		 cost:{cash:0,gem:0,storage:[]},
		 shareName:"vipSuperbombNum1",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"NumCapSuperbomb",add:1},
		  {scope:"City",name:"MaxCapSuperbomb",add:1},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipSuperbombNum1"]);
		defLib["vipSuperbombNum2"]={
		 codeName:"vipSuperbombNum2",
		 icon:"",durTime:172800000,
		 cost:{cash:0,gem:0,storage:[]},
		 shareName:"vipSuperbombNum2",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"NumCapSuperbomb",add:2},
		  {scope:"City",name:"MaxCapSuperbomb",add:2},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipSuperbombNum2"]);
		defLib["vipSuperbombNum3"]={
		 codeName:"vipSuperbombNum3",
		 icon:"",durTime:172800000,
		 cost:{cash:0,gem:0,storage:[]},
		 shareName:"vipSuperbombNum3",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"NumCapSuperbomb",add:3},
		  {scope:"City",name:"MaxCapSuperbomb",add:3},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipSuperbombNum3"]);
		defLib["vipGemRush30"]={
		 codeName:"vipGemRush30",
		 icon:"",durTime:604800000,
		 cost:defLib["GemRush"].cost,
		 shareName:"vipGemRush30",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"DiamondMineMax",add:30},
		  {scope:"City",name:"DiamondMineHarvest",add:30},
		  {scope:"City",name:"DiamondMineSpeed",add:0.0003472222222222222},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipGemRush30"]);
		defLib["vipGemRush35"]={
		 codeName:"vipGemRush35",
		 icon:"",durTime:604800000,
		 cost:defLib["GemRush"].cost,
		 shareName:"vipGemRush35",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"DiamondMineMax",add:35},
		  {scope:"City",name:"DiamondMineHarvest",add:35},
		  {scope:"City",name:"DiamondMineSpeed",add:0.0004050925925925926},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipGemRush35"]);
		defLib["vipGemRush40"]={
		 codeName:"vipGemRush40",
		 icon:"",durTime:604800000,
		 cost:defLib["GemRush"].cost,
		 shareName:"vipGemRush40",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"DiamondMineMax",add:40},
		  {scope:"City",name:"DiamondMineHarvest",add:40},
		  {scope:"City",name:"DiamondMineSpeed",add:0.000462962962962963},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipGemRush40"]);
		defLib["vipGemRush45"]={
		 codeName:"vipGemRush45",
		 icon:"",durTime:604800000,
		 cost:defLib["GemRush"].cost,
		 shareName:"vipGemRush45",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"DiamondMineMax",add:45},
		  {scope:"City",name:"DiamondMineHarvest",add:45},
		  {scope:"City",name:"DiamondMineSpeed",add:0.0005208333333333333},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipGemRush45"]);
		defLib["vipGemRush50"]={
		 codeName:"vipGemRush50",
		 icon:"",durTime:604800000,
		 cost:defLib["GemRush"].cost,
		 shareName:"vipGemRush50",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"DiamondMineMax",add:50},
		  {scope:"City",name:"DiamondMineHarvest",add:50},
		  {scope:"City",name:"DiamondMineSpeed",add:0.0005787037037037038},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipGemRush50"]);
		defLib["vipGemRush60"]={
		 codeName:"vipGemRush60",
		 icon:"",durTime:604800000,
		 cost:defLib["GemRush"].cost,
		 shareName:"vipGemRush60",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"DiamondMineMax",add:60},
		  {scope:"City",name:"DiamondMineHarvest",add:60},
		  {scope:"City",name:"DiamondMineSpeed",add:0.0006944444444444444},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipGemRush60"]);
		defLib["vipGemRush70"]={
		 codeName:"vipGemRush70",
		 icon:"",durTime:604800000,
		 cost:defLib["GemRush"].cost,
		 shareName:"vipGemRush70",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"DiamondMineMax",add:70},
		  {scope:"City",name:"DiamondMineHarvest",add:70},
		  {scope:"City",name:"DiamondMineSpeed",add:0.0008101851851851852},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipGemRush70"]);
		defLib["vipGemRush80"]={
		 codeName:"vipGemRush80",
		 icon:"",durTime:604800000,
		 cost:defLib["GemRush"].cost,
		 shareName:"vipGemRush80",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"DiamondMineMax",add:80},
		  {scope:"City",name:"DiamondMineHarvest",add:80},
		  {scope:"City",name:"DiamondMineSpeed",add:0.000925925925925926},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipGemRush80"]);
		defLib["vipGemRush90"]={
		 codeName:"vipGemRush90",
		 icon:"",durTime:604800000,
		 cost:defLib["GemRush"].cost,
		 shareName:"vipGemRush90",type:"VipBldBoost",
		 factors:[
		  {scope:"City",name:"DiamondMineMax",add:90},
		  {scope:"City",name:"DiamondMineHarvest",add:90},
		  {scope:"City",name:"DiamondMineSpeed",add:0.0010416666666666666},
		 ]
		};
		window.aisEnv.defLib.hashFactors(defLib["vipGemRush90"]);
	})();
}
