if(window.aisEnv.defLib && window.aisEnv.defLib.box && !window.aisEnv.defLib.box.inited)
{
	(function()
	{
		var defLib=window.aisEnv.defLib.box;
		var textLib=window.aisEnv.textLib;
		defLib.inited=1;
		defLib["box1"]={
		 codeName:"box1",FreeTimes:1,TotalTimes:10000000,name:textLib.boxName["box1"],desc:textLib.boxInfo["box1"],icon:"box_box1",IsShow:true,
		 cost:{time:0,cash:0,gem:35,storage:[]},
		 boxs:[
		  {type:"Gem",catalog:"Gem",num:200,rare:true},
		  {type:"ResGold",catalog:"Res",num:200000,rare:false},
		  {type:"ResGold",catalog:"Res",num:1000000,rare:false},
		  {type:"ResGold",catalog:"Res",num:8000000,rare:true},
		  {type:"ResCube",catalog:"Res",num:1000,rare:false},
		  {type:"ResCube",catalog:"Res",num:2000,rare:false},
		  {type:"ResOil",catalog:"Res",num:200000,rare:false},
		  {type:"ResOil",catalog:"Res",num:500000,rare:false},
		  {type:"itm_token_4",catalog:"Item",num:3,rare:true},
		  {type:"par_body05_04",catalog:"Par",num:1,rare:true},
		  {type:"itm_token_3",catalog:"Item",num:2,rare:true},
		  {type:"plu_comup_02",catalog:"Plu",num:1,rare:false},
		  {type:"itm_token_1",catalog:"Item",num:5,rare:false},
		  {type:"plu_L7_04",catalog:"Plu",num:1,rare:true},
		  {type:"plu_L2_02",catalog:"Plu",num:1,rare:false},
		  {type:"plu_L3_04",catalog:"Plu",num:1,rare:false},
		 ]
		};
		defLib["box2"]={
		 codeName:"box2",FreeTimes:0,TotalTimes:10000000,name:textLib.boxName["box2"],desc:textLib.boxInfo["box2"],icon:"box_box2",IsShow:true,
		 cost:{time:0,cash:0,gem:200,storage:[]},
		 boxs:[
		  {type:"par_body07_04",catalog:"Par",num:1,rare:true},
		  {type:"par_body05_04",catalog:"Par",num:1,rare:true},
		  {type:"plu_L7_04",catalog:"Plu",num:1,rare:true},
		  {type:"plu_L5_07",catalog:"Plu",num:1,rare:false},
		  {type:"itm_token_1",catalog:"Item",num:10,rare:false},
		  {type:"itm_token_2",catalog:"Item",num:20,rare:true},
		  {type:"Gem",catalog:"Gem",num:1000,rare:true},
		  {type:"plu_comup_03",catalog:"Plu",num:1,rare:true},
		  {type:"plu_comup_02",catalog:"Plu",num:1,rare:false},
		  {type:"itm_token_2",catalog:"Item",num:5,rare:false},
		  {type:"ResOil",catalog:"Res",num:1000000,rare:false},
		  {type:"ResGold",catalog:"Res",num:1000000,rare:false},
		  {type:"ResGold",catalog:"Res",num:2000000,rare:false},
		  {type:"ResGold",catalog:"Res",num:8000000,rare:true},
		  {type:"ResCube",catalog:"Res",num:10000,rare:false},
		  {type:"ResCube",catalog:"Res",num:30000,rare:true},
		 ]
		};
		defLib["box3"]={
		 codeName:"box3",FreeTimes:0,TotalTimes:10000000,name:textLib.boxName["box3"],desc:textLib.boxInfo["box3"],icon:"box_box3",IsShow:false,
		 cost:{time:0,cash:0,gem:10,storage:[]},
		 boxs:[
		  {type:"Gem",catalog:"Gem",num:200,rare:true},
		  {type:"ResGold",catalog:"Res",num:500000,rare:false},
		  {type:"ResCube",catalog:"Res",num:1000,rare:false},
		  {type:"ResCube",catalog:"Res",num:2000,rare:false},
		  {type:"ResOil",catalog:"Res",num:500000,rare:false},
		  {type:"plu_comup_02",catalog:"Plu",num:1,rare:true},
		  {type:"plu_comup_01",catalog:"Plu",num:1,rare:false},
		  {type:"plu_L3_01",catalog:"Plu",num:1,rare:false},
		  {type:"plu_L4_01",catalog:"Plu",num:1,rare:false},
		  {type:"plu_L9_07",catalog:"Plu",num:1,rare:true},
		 ]
		};
		defLib["box4"]={
		 codeName:"box4",FreeTimes:0,TotalTimes:10000000,name:textLib.boxName["box4"],desc:textLib.boxInfo["box4"],icon:"box_box4",IsShow:false,
		 cost:{time:0,cash:0,gem:10,storage:[]},
		 boxs:[
		  {type:"Gem",catalog:"Gem",num:200,rare:true},
		  {type:"ResGold",catalog:"Res",num:800000,rare:true},
		  {type:"ResCube",catalog:"Res",num:1500,rare:false},
		  {type:"ResCube",catalog:"Res",num:3000,rare:true},
		  {type:"ResOil",catalog:"Res",num:800000,rare:true},
		  {type:"plu_comup_02",catalog:"Plu",num:1,rare:false},
		  {type:"ResGold",catalog:"Res",num:1500000,rare:true},
		  {type:"plu_L4_07",catalog:"Plu",num:1,rare:false},
		  {type:"plu_L4_08",catalog:"Plu",num:1,rare:false},
		  {type:"plu_L9_07",catalog:"Plu",num:1,rare:true},
		 ]
		};
		defLib["box5"]={
		 codeName:"box5",FreeTimes:0,TotalTimes:10000000,name:textLib.boxName["box5"],desc:textLib.boxInfo["box5"],icon:"box_box5",IsShow:false,
		 cost:{time:0,cash:0,gem:10,storage:[]},
		 boxs:[
		  {type:"Gem",catalog:"Gem",num:200,rare:true},
		  {type:"ResGold",catalog:"Res",num:800000,rare:true},
		  {type:"ResCube",catalog:"Res",num:1500,rare:false},
		  {type:"ResCube",catalog:"Res",num:3000,rare:true},
		  {type:"ResOil",catalog:"Res",num:800000,rare:true},
		  {type:"plu_comup_02",catalog:"Plu",num:1,rare:false},
		  {type:"ResGold",catalog:"Res",num:1500000,rare:true},
		  {type:"plu_L4_07",catalog:"Plu",num:1,rare:false},
		  {type:"plu_L4_08",catalog:"Plu",num:1,rare:false},
		  {type:"plu_L9_07",catalog:"Plu",num:1,rare:true},
		 ]
		};
	})();
}
