if(window.aisEnv.defLib && window.aisEnv.defLib.dailytasks && !window.aisEnv.defLib.dailytasks.inited)
{
	(function()
	{
		var defLib=window.aisEnv.defLib.dailytasks;
		var textLib=window.aisEnv.textLib;
		defLib.inited=1;
		defLib["loot_gold_2"]={
		codeName:"loot_gold_2",type:"loot",name:textLib.dailytasksName["loot_gold_2"],desc:textLib.dailytasksInfo["loot_gold_2"],icon:"dailytasks_loot_gold_2",
		bldType:"Gold",
		levels:[
			{score:50000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:50000},],},
			{score:100000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:50000},],},
			{score:350000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:100000},],},
			{score:500000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:100000},],},
			]
		};
		defLib["loot_elixir_2"]={
		codeName:"loot_elixir_2",type:"loot",name:textLib.dailytasksName["loot_elixir_2"],desc:textLib.dailytasksInfo["loot_elixir_2"],icon:"dailytasks_loot_elixir_2",
		bldType:"Elixir",
		levels:[
			{score:50000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:50000},],},
			{score:100000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:50000},],},
			{score:350000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:100000},],},
			{score:500000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:100000},],},
			]
		};
		defLib["loot_gold_3"]={
		codeName:"loot_gold_3",type:"loot",name:textLib.dailytasksName["loot_gold_3"],desc:textLib.dailytasksInfo["loot_gold_3"],icon:"dailytasks_loot_gold_3",
		bldType:"Gold",
		levels:[
			{score:50000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:50000},],},
			{score:100000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:50000},],},
			{score:350000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:100000},],},
			{score:500000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:100000},],},
			]
		};
		defLib["loot_elixir_3"]={
		codeName:"loot_elixir_3",type:"loot",name:textLib.dailytasksName["loot_elixir_3"],desc:textLib.dailytasksInfo["loot_elixir_3"],icon:"dailytasks_loot_elixir_3",
		bldType:"Elixir",
		levels:[
			{score:50000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:50000},],},
			{score:100000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:50000},],},
			{score:350000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:100000},],},
			{score:500000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:100000},],},
			]
		};
		defLib["loot_gold_4"]={
		codeName:"loot_gold_4",type:"loot",name:textLib.dailytasksName["loot_gold_4"],desc:textLib.dailytasksInfo["loot_gold_4"],icon:"dailytasks_loot_gold_4",
		bldType:"Gold",
		levels:[
			{score:5000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:30000},],},
			{score:20000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:50000},],},
			{score:50000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:50000},],},
			{score:100000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:100000},],},
			]
		};
		defLib["loot_elixir_4"]={
		codeName:"loot_elixir_4",type:"loot",name:textLib.dailytasksName["loot_elixir_4"],desc:textLib.dailytasksInfo["loot_elixir_4"],icon:"dailytasks_loot_elixir_4",
		bldType:"Elixir",
		levels:[
			{score:5000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:30000},],},
			{score:20000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:50000},],},
			{score:50000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:50000},],},
			{score:100000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:100000},],},
			]
		};
		defLib["loot_gold_5"]={
		codeName:"loot_gold_5",type:"loot",name:textLib.dailytasksName["loot_gold_5"],desc:textLib.dailytasksInfo["loot_gold_5"],icon:"dailytasks_loot_gold_5",
		bldType:"Gold",
		levels:[
			{score:10000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:50000},],},
			{score:50000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:50000},],},
			{score:100000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:100000},],},
			{score:300000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:150000},],},
			]
		};
		defLib["loot_elixir_5"]={
		codeName:"loot_elixir_5",type:"loot",name:textLib.dailytasksName["loot_elixir_5"],desc:textLib.dailytasksInfo["loot_elixir_5"],icon:"dailytasks_loot_elixir_5",
		bldType:"Elixir",
		levels:[
			{score:10000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:50000},],},
			{score:50000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:50000},],},
			{score:100000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:100000},],},
			{score:300000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:150000},],},
			]
		};
		defLib["loot_gold_6"]={
		codeName:"loot_gold_6",type:"loot",name:textLib.dailytasksName["loot_gold_6"],desc:textLib.dailytasksInfo["loot_gold_6"],icon:"dailytasks_loot_gold_6",
		bldType:"Gold",
		levels:[
			{score:50000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:50000},],},
			{score:100000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:100000},],},
			{score:300000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:100000},],},
			{score:1000000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:200000},],},
			]
		};
		defLib["loot_elixir_6"]={
		codeName:"loot_elixir_6",type:"loot",name:textLib.dailytasksName["loot_elixir_6"],desc:textLib.dailytasksInfo["loot_elixir_6"],icon:"dailytasks_loot_elixir_6",
		bldType:"Elixir",
		levels:[
			{score:50000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:50000},],},
			{score:100000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:100000},],},
			{score:300000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:100000},],},
			{score:1000000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:200000},],},
			]
		};
		defLib["loot_gold_7"]={
		codeName:"loot_gold_7",type:"loot",name:textLib.dailytasksName["loot_gold_7"],desc:textLib.dailytasksInfo["loot_gold_7"],icon:"dailytasks_loot_gold_7",
		bldType:"Gold",
		levels:[
			{score:100000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:100000},],},
			{score:500000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:150000},],},
			{score:1000000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:200000},],},
			{score:3000000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:300000},],},
			]
		};
		defLib["loot_elixir_7"]={
		codeName:"loot_elixir_7",type:"loot",name:textLib.dailytasksName["loot_elixir_7"],desc:textLib.dailytasksInfo["loot_elixir_7"],icon:"dailytasks_loot_elixir_7",
		bldType:"Elixir",
		levels:[
			{score:100000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:100000},],},
			{score:500000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:150000},],},
			{score:1000000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:200000},],},
			{score:3000000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:300000},],},
			]
		};
		defLib["loot_gold_8"]={
		codeName:"loot_gold_8",type:"loot",name:textLib.dailytasksName["loot_gold_8"],desc:textLib.dailytasksInfo["loot_gold_8"],icon:"dailytasks_loot_gold_8",
		bldType:"Gold",
		levels:[
			{score:100000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:300000},],},
			{score:500000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:500000},],},
			{score:2000000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:1000000},],},
			{score:5000000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:2000000},],},
			]
		};
		defLib["loot_elixir_8"]={
		codeName:"loot_elixir_8",type:"loot",name:textLib.dailytasksName["loot_elixir_8"],desc:textLib.dailytasksInfo["loot_elixir_8"],icon:"dailytasks_loot_elixir_8",
		bldType:"Elixir",
		levels:[
			{score:100000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:300000},],},
			{score:500000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:500000},],},
			{score:2000000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:1000000},],},
			{score:5000000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:2000000},],},
			]
		};
		defLib["loot_gold_9"]={
		codeName:"loot_gold_9",type:"loot",name:textLib.dailytasksName["loot_gold_9"],desc:textLib.dailytasksInfo["loot_gold_9"],icon:"dailytasks_loot_gold_9",
		bldType:"Gold",
		levels:[
			{score:100000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:300000},],},
			{score:500000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:500000},],},
			{score:2000000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:1000000},],},
			{score:5000000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:2000000},],},
			]
		};
		defLib["loot_elixir_9"]={
		codeName:"loot_elixir_9",type:"loot",name:textLib.dailytasksName["loot_elixir_9"],desc:textLib.dailytasksInfo["loot_elixir_9"],icon:"dailytasks_loot_elixir_9",
		bldType:"Elixir",
		levels:[
			{score:100000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:300000},],},
			{score:500000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:500000},],},
			{score:2000000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:1000000},],},
			{score:5000000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:2000000},],},
			]
		};
		defLib["loot_gold_10"]={
		codeName:"loot_gold_10",type:"loot",name:textLib.dailytasksName["loot_gold_10"],desc:textLib.dailytasksInfo["loot_gold_10"],icon:"dailytasks_loot_gold_10",
		bldType:"Gold",
		levels:[
			{score:100000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:300000},],},
			{score:500000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:500000},],},
			{score:2000000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:1000000},],},
			{score:5000000,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:2000000},],},
			]
		};
		defLib["loot_elixir_10"]={
		codeName:"loot_elixir_10",type:"loot",name:textLib.dailytasksName["loot_elixir_10"],desc:textLib.dailytasksInfo["loot_elixir_10"],icon:"dailytasks_loot_elixir_10",
		bldType:"Elixir",
		levels:[
			{score:100000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:300000},],},
			{score:500000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:500000},],},
			{score:2000000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:1000000},],},
			{score:5000000,RewardTypeCount:1,Reward:[{RewardType:"Elixir",RewardRes:2000000},],},
			]
		};
		defLib["battle_star_4"]={
		codeName:"battle_star_4",type:"battle",name:textLib.dailytasksName["battle_star_4"],desc:textLib.dailytasksInfo["battle_star_4"],icon:"dailytasks_battle_star_4",
		bldType:"Star",
		levels:[
			{score:3,RewardTypeCount:1,Reward:[{RewardType:"Cube",RewardRes:500},],},
			{score:40,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:1000000},],},
			{score:45,RewardTypeCount:1,Reward:[{RewardType:"Cube",RewardRes:1500},],},
			{score:50,RewardTypeCount:1,Reward:[{RewardType:"Cube",RewardRes:500},],},
			]
		};
		defLib["battle_star_5"]={
		codeName:"battle_star_5",type:"battle",name:textLib.dailytasksName["battle_star_5"],desc:textLib.dailytasksInfo["battle_star_5"],icon:"dailytasks_battle_star_5",
		bldType:"Star",
		levels:[
			{score:3,RewardTypeCount:1,Reward:[{RewardType:"Cube",RewardRes:500},],},
			{score:40,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:1000000},],},
			{score:45,RewardTypeCount:1,Reward:[{RewardType:"Cube",RewardRes:1500},],},
			{score:50,RewardTypeCount:1,Reward:[{RewardType:"Cube",RewardRes:500},],},
			]
		};
		defLib["battle_star_6"]={
		codeName:"battle_star_6",type:"battle",name:textLib.dailytasksName["battle_star_6"],desc:textLib.dailytasksInfo["battle_star_6"],icon:"dailytasks_battle_star_6",
		bldType:"Star",
		levels:[
			{score:3,RewardTypeCount:1,Reward:[{RewardType:"Cube",RewardRes:500},],},
			{score:40,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:1000000},],},
			{score:45,RewardTypeCount:1,Reward:[{RewardType:"Cube",RewardRes:1500},],},
			{score:50,RewardTypeCount:1,Reward:[{RewardType:"Cube",RewardRes:500},],},
			]
		};
		defLib["battle_star_7"]={
		codeName:"battle_star_7",type:"battle",name:textLib.dailytasksName["battle_star_7"],desc:textLib.dailytasksInfo["battle_star_7"],icon:"dailytasks_battle_star_7",
		bldType:"Star",
		levels:[
			{score:3,RewardTypeCount:1,Reward:[{RewardType:"Cube",RewardRes:500},],},
			{score:40,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:2000000},],},
			{score:45,RewardTypeCount:1,Reward:[{RewardType:"Cube",RewardRes:2000},],},
			{score:50,RewardTypeCount:1,Reward:[{RewardType:"Cube",RewardRes:500},],},
			]
		};
		defLib["battle_star_8"]={
		codeName:"battle_star_8",type:"battle",name:textLib.dailytasksName["battle_star_8"],desc:textLib.dailytasksInfo["battle_star_8"],icon:"dailytasks_battle_star_8",
		bldType:"Star",
		levels:[
			{score:3,RewardTypeCount:1,Reward:[{RewardType:"Cube",RewardRes:500},],},
			{score:40,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:2000000},],},
			{score:45,RewardTypeCount:1,Reward:[{RewardType:"Cube",RewardRes:2000},],},
			{score:50,RewardTypeCount:1,Reward:[{RewardType:"Cube",RewardRes:500},],},
			]
		};
		defLib["battle_star_9"]={
		codeName:"battle_star_9",type:"battle",name:textLib.dailytasksName["battle_star_9"],desc:textLib.dailytasksInfo["battle_star_9"],icon:"dailytasks_battle_star_9",
		bldType:"Star",
		levels:[
			{score:3,RewardTypeCount:1,Reward:[{RewardType:"Cube",RewardRes:500},],},
			{score:40,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:2000000},],},
			{score:45,RewardTypeCount:1,Reward:[{RewardType:"Cube",RewardRes:2000},],},
			{score:50,RewardTypeCount:1,Reward:[{RewardType:"Cube",RewardRes:500},],},
			]
		};
		defLib["battle_star_10"]={
		codeName:"battle_star_10",type:"battle",name:textLib.dailytasksName["battle_star_10"],desc:textLib.dailytasksInfo["battle_star_10"],icon:"dailytasks_battle_star_10",
		bldType:"Star",
		levels:[
			{score:3,RewardTypeCount:1,Reward:[{RewardType:"Cube",RewardRes:500},],},
			{score:40,RewardTypeCount:1,Reward:[{RewardType:"Gold",RewardRes:2000000},],},
			{score:45,RewardTypeCount:1,Reward:[{RewardType:"Cube",RewardRes:2000},],},
			{score:50,RewardTypeCount:1,Reward:[{RewardType:"Cube",RewardRes:500},],},
			]
		};
	})();
}
