if(window.aisEnv.defLib && window.aisEnv.defLib.feature && !window.aisEnv.defLib.feature.inited)
{
	//特性的DEF:
	(function()
	{
		var defLib=window.aisEnv.defLib.feature;
		var textLib=window.aisEnv.textLib;
		defLib.inited=1;
		//主基地等级
		{
			defLib["TownHall_Lv1"]={
				codeName:"TownHall_Lv1",icon:"bld_townhall",name:textLib.bldName["TownHall_Lv1"],info:textLib.ftuInfo["townhall_lv1"],
			};
			defLib["TownHall_Lv2"]={
				codeName:"TownHall_Lv2",icon:"bld_townhall",name:textLib.bldName["TownHall_Lv2"],info:textLib.ftuInfo["townhall_lv2"],
			};
			defLib["TownHall_Lv3"]={
				codeName:"TownHall_Lv3",icon:"bld_townhall",name:textLib.bldName["TownHall_Lv3"],info:textLib.ftuInfo["townhall_lv3"],
			};
			defLib["TownHall_Lv4"]={
				codeName:"TownHall_Lv4",icon:"bld_townhall",name:textLib.bldName["TownHall_Lv4"],info:textLib.ftuInfo["townhall_lv4"],
			};
			defLib["TownHall_Lv5"]={
				codeName:"TownHall_Lv5",icon:"bld_townhall",name:textLib.bldName["TownHall_Lv5"],info:textLib.ftuInfo["townhall_lv5"],
			};
			defLib["TownHall_Lv6"]={
				codeName:"TownHall_Lv6",icon:"bld_townhall",name:textLib.bldName["TownHall_Lv6"],info:textLib.ftuInfo["townhall_lv6"],
			};
			defLib["TownHall_Lv7"]={
				codeName:"TownHall_Lv7",icon:"bld_townhall",name:textLib.bldName["TownHall_Lv7"],info:textLib.ftuInfo["townhall_lv7"],
			};
			defLib["TownHall_Lv8"]={
				codeName:"TownHall_Lv8",icon:"bld_townhall",name:textLib.bldName["TownHall_Lv8"],info:textLib.ftuInfo["townhall_lv8"],
			};
			defLib["TownHall_Lv9"]={
				codeName:"TownHall_Lv8",icon:"bld_townhall",name:textLib.bldName["TownHall_Lv9"],info:textLib.ftuInfo["townhall_lv9"],
			};
			defLib["TownHall_Lv10"]={
				codeName:"TownHall_Lv10",icon:"bld_townhall",name:textLib.bldName["TownHall_Lv10"],info:textLib.ftuInfo["townhall_lv10"],
			};
		}
		//兵营等级
		{
			defLib["Barrack_Lv1"]={
				codeName:"Barrack_Lv1",icon:"bld_barrack",name:textLib.bldName["Barrack_Lv1"],info:textLib.ftuInfo["barrack_lv1"],
			};
			defLib["Barrack_Lv2"]={
				codeName:"Barrack_Lv2",icon:"bld_barrack",name:textLib.bldName["Barrack_Lv2"],info:textLib.ftuInfo["barrack_lv2"],
			};
			defLib["Barrack_Lv3"]={
				codeName:"Barrack_Lv3",icon:"bld_barrack",name:textLib.bldName["Barrack_Lv3"],info:textLib.ftuInfo["barrack_lv3"],
			};
			defLib["Barrack_Lv4"]={
				codeName:"Barrack_Lv4",icon:"bld_barrack",name:textLib.bldName["Barrack_Lv4"],info:textLib.ftuInfo["barrack_lv4"],
			};
			defLib["Barrack_Lv5"]={
				codeName:"Barrack_Lv5",icon:"bld_barrack",name:textLib.bldName["Barrack_Lv5"],info:textLib.ftuInfo["barrack_lv5"],
			};
			defLib["Barrack_Lv6"]={
				codeName:"Barrack_Lv6",icon:"bld_barrack",name:textLib.bldName["Barrack_Lv6"],info:textLib.ftuInfo["barrack_lv6"],
			};
			defLib["Barrack_Lv7"]={
				codeName:"Barrack_Lv7",icon:"bld_barrack",name:textLib.bldName["Barrack_Lv7"],info:textLib.ftuInfo["barrack_lv7"],
			};
			defLib["Barrack_Lv8"]={
				codeName:"Barrack_Lv8",icon:"bld_barrack",name:textLib.bldName["Barrack_Lv8"],info:textLib.ftuInfo["barrack_lv8"],
			};
			defLib["Barrack_Lv9"]={
				codeName:"Barrack_Lv8",icon:"bld_barrack",name:textLib.bldName["Barrack_Lv9"],info:textLib.ftuInfo["barrack_lv9"],
			};
			defLib["Barrack_Lv10"]={
				codeName:"Barrack_Lv10",icon:"bld_barrack",name:textLib.bldName["Barrack_Lv10"],info:textLib.ftuInfo["barrack_lv10"],
			};
		}
		//实验室等级
		{
			defLib["SpellLab_Lv1"]={
				codeName:"SpellLab_Lv1",icon:"bld_spellLab",name:textLib.bldName["SpellLab_Lv1"],info:textLib.ftuInfo["spellLab_lv1"],
			};
			defLib["SpellLab_Lv2"]={
				codeName:"SpellLab_Lv2",icon:"bld_spellLab",name:textLib.bldName["SpellLab_Lv2"],info:textLib.ftuInfo["spellLab_lv2"],
			};
			defLib["SpellLab_Lv3"]={
				codeName:"SpellLab_Lv3",icon:"bld_spellLab",name:textLib.bldName["SpellLab_Lv3"],info:textLib.ftuInfo["spellLab_lv3"],
			};
			defLib["SpellLab_Lv4"]={
				codeName:"SpellLab_Lv4",icon:"bld_spellLab",name:textLib.bldName["SpellLab_Lv4"],info:textLib.ftuInfo["spellLab_lv4"],
			};
			defLib["SpellLab_Lv5"]={
				codeName:"SpellLab_Lv5",icon:"bld_spellLab",name:textLib.bldName["SpellLab_Lv5"],info:textLib.ftuInfo["spellLab_lv5"],
			};
			defLib["SpellLab_Lv6"]={
				codeName:"SpellLab_Lv6",icon:"bld_spellLab",name:textLib.bldName["SpellLab_Lv6"],info:textLib.ftuInfo["spellLab_lv6"],
			};
		}
		//研究所等级
		{
			defLib["TechLab_Lv1"]={
				codeName:"TechLab_Lv1",icon:"bld_techLab",name:textLib.bldName["TechLab_Lv1"],info:textLib.ftuInfo["techLab_lv1"],
			};
			defLib["TechLab_Lv2"]={
				codeName:"TechLab_Lv2",icon:"bld_techLab",name:textLib.bldName["TechLab_Lv2"],info:textLib.ftuInfo["techLab_lv2"],
			};
			defLib["TechLab_Lv3"]={
				codeName:"TechLab_Lv3",icon:"bld_techLab",name:textLib.bldName["TechLab_Lv3"],info:textLib.ftuInfo["techLab_lv3"],
			};
			defLib["TechLab_Lv4"]={
				codeName:"TechLab_Lv4",icon:"bld_techLab",name:textLib.bldName["TechLab_Lv4"],info:textLib.ftuInfo["techLab_lv4"],
			};
			defLib["TechLab_Lv5"]={
				codeName:"TechLab_Lv5",icon:"bld_techLab",name:textLib.bldName["TechLab_Lv5"],info:textLib.ftuInfo["techLab_lv5"],
			};
			defLib["TechLab_Lv6"]={
				codeName:"TechLab_Lv6",icon:"bld_techLab",name:textLib.bldName["TechLab_Lv6"],info:textLib.ftuInfo["techLab_lv6"],
			};
			defLib["TechLab_Lv7"]={
				codeName:"TechLab_Lv7",icon:"bld_techLab",name:textLib.bldName["TechLab_Lv7"],info:textLib.ftuInfo["techLab_lv7"],
			};
			defLib["TechLab_Lv8"]={
				codeName:"TechLab_Lv8",icon:"bld_techLab",name:textLib.bldName["TechLab_Lv8"],info:textLib.ftuInfo["techLab_lv8"],
			};
		}
	})();
}
