if(window.aisEnv.defLib && window.aisEnv.defLib.clan && !window.aisEnv.defLib.clan.inited)
{
	(function()
	{
		var defLib=window.aisEnv.defLib.clanTec;
		var textLib=window.aisEnv.textLib;
		defLib["Tec_TrainingSpeed"]={
		 codeName:"Tec_TrainingSpeed",showType:0,
		 levels:[
		 {level:1,name:textLib.clantecName["Tec_TrainingSpeed_Lv1"],desc:textLib.clantecInfo["Tec_TrainingSpeed_Lv1"],
		 expireTime:24,scope:"Barrack",scopeVar:"TrainingTime",scopeType:2,scopeValue:75,
		  cost:{cash:0,gem:1000,storage:[]},
		  callCost:{cash:0,gem:20,storage:[]},
		 },
		 {level:2,name:textLib.clantecName["Tec_TrainingSpeed_Lv2"],desc:textLib.clantecInfo["Tec_TrainingSpeed_Lv2"],
		 expireTime:24,scope:"Barrack",scopeVar:"TrainingTime",scopeType:2,scopeValue:50,
		  cost:{cash:0,gem:2000,storage:[]},
		  callCost:{cash:0,gem:25,storage:[]},
		 },
		 {level:3,name:textLib.clantecName["Tec_TrainingSpeed_Lv3"],desc:textLib.clantecInfo["Tec_TrainingSpeed_Lv3"],
		 expireTime:24,scope:"Barrack",scopeVar:"TrainingTime",scopeType:2,scopeValue:25,
		  cost:{cash:0,gem:4000,storage:[]},
		  callCost:{cash:0,gem:40,storage:[]},
		 },
			]
		};
		defLib["Tec_TownHallHP"]={
		 codeName:"Tec_TownHallHP",showType:1,
		 levels:[
		 {level:1,name:textLib.clantecName["Tec_TownHallHP_Lv1"],desc:textLib.clantecInfo["Tec_TownHallHP_Lv1"],
		 expireTime:24,scope:"TownHall",scopeVar:"Hitpoints",scopeType:2,scopeValue:150,
		  cost:{cash:0,gem:350,storage:[]},
		  callCost:{cash:0,gem:5,storage:[]},
		 },
		 {level:2,name:textLib.clantecName["Tec_TownHallHP_Lv2"],desc:textLib.clantecInfo["Tec_TownHallHP_Lv2"],
		 expireTime:24,scope:"TownHall",scopeVar:"Hitpoints",scopeType:2,scopeValue:175,
		  cost:{cash:0,gem:700,storage:[]},
		  callCost:{cash:0,gem:7,storage:[]},
		 },
		 {level:3,name:textLib.clantecName["Tec_TownHallHP_Lv3"],desc:textLib.clantecInfo["Tec_TownHallHP_Lv3"],
		 expireTime:24,scope:"TownHall",scopeVar:"Hitpoints",scopeType:2,scopeValue:200,
		  cost:{cash:0,gem:1400,storage:[]},
		  callCost:{cash:0,gem:14,storage:[]},
		 },
			]
		};
		defLib["Tec_ResourceMax"]={
		 codeName:"Tec_ResourceMax",showType:2,
		 levels:[
		 {level:1,name:textLib.clantecName["Tec_ResourceMax_Lv1"],desc:textLib.clantecInfo["Tec_ResourceMax_Lv1"],
		 expireTime:24,scope:"Res",scopeVar:"BattleMax",scopeType:1,scopeValue:300000,
		  cost:{cash:0,gem:1400,storage:[]},
		  callCost:{cash:0,gem:20,storage:[]},
		 },
		 {level:2,name:textLib.clantecName["Tec_ResourceMax_Lv2"],desc:textLib.clantecInfo["Tec_ResourceMax_Lv2"],
		 expireTime:24,scope:"Res",scopeVar:"BattleMax",scopeType:1,scopeValue:400000,
		  cost:{cash:0,gem:2000,storage:[]},
		  callCost:{cash:0,gem:25,storage:[]},
		 },
		 {level:3,name:textLib.clantecName["Tec_ResourceMax_Lv3"],desc:textLib.clantecInfo["Tec_ResourceMax_Lv3"],
		 expireTime:24,scope:"Res",scopeVar:"BattleMax",scopeType:1,scopeValue:500000,
		  cost:{cash:0,gem:2700,storage:[]},
		  callCost:{cash:0,gem:27,storage:[]},
		 },
			]
		};
		defLib["Tec_TrapUp"]={
		 codeName:"Tec_TrapUp",showType:1,
		 levels:[
		 {level:1,name:textLib.clantecName["Tec_TrapUp_Lv1"],desc:textLib.clantecInfo["Tec_TrapUp_Lv1"],
		 expireTime:24,scope:"Traps",scopeVar:"Damage",scopeType:2,scopeValue:140,
		  cost:{cash:0,gem:700,storage:[]},
		  callCost:{cash:0,gem:10,storage:[]},
		 },
		 {level:2,name:textLib.clantecName["Tec_TrapUp_Lv2"],desc:textLib.clantecInfo["Tec_TrapUp_Lv2"],
		 expireTime:24,scope:"Traps",scopeVar:"Damage",scopeType:2,scopeValue:180,
		  cost:{cash:0,gem:1400,storage:[]},
		  callCost:{cash:0,gem:14,storage:[]},
		 },
			]
		};
		defLib["Tec_DefenseUp"]={
		 codeName:"Tec_DefenseUp",showType:1,
		 levels:[
		 {level:1,name:textLib.clantecName["Tec_DefenseUp_Lv1"],desc:textLib.clantecInfo["Tec_DefenseUp_Lv1"],
		 expireTime:24,scope:"Defense",scopeVar:"Damage",scopeType:2,scopeValue:110,
		  cost:{cash:0,gem:1000,storage:[]},
		  callCost:{cash:0,gem:10,storage:[]},
		 },
		 {level:2,name:textLib.clantecName["Tec_DefenseUp_Lv2"],desc:textLib.clantecInfo["Tec_DefenseUp_Lv2"],
		 expireTime:24,scope:"Defense",scopeVar:"Damage",scopeType:2,scopeValue:120,
		  cost:{cash:0,gem:2000,storage:[]},
		  callCost:{cash:0,gem:20,storage:[]},
		 },
			]
		};

		var defLib=window.aisEnv.defLib.buff;
		defLib["Tec_TrainingSpeed1"]={
			codeName:"Tec_TrainingSpeed1",name:"",desc:"",
			icon:"",durTime:86400000,
			cost:{cash:0,gem:0,storage:[]},
			shareName:"Tec_TrainingSpeed1",type:"BldBoost",
			factors:[
				{scope:"Building",name:"MFCSpeed",mbf:1.3333333333333332},
			]
		};
		if(window.aisEnv.defLib.hashFactors)
		window.aisEnv.defLib.hashFactors(defLib["Tec_TrainingSpeed1"]);

		defLib["Tec_TrainingSpeed2"]={
			codeName:"Tec_TrainingSpeed2",name:"",desc:"",
			icon:"",durTime:86400000,
			cost:{cash:0,gem:0,storage:[]},
			shareName:"Tec_TrainingSpeed2",type:"BldBoost",
			factors:[
				{scope:"Building",name:"MFCSpeed",mbf:2},
			]
		};
		if(window.aisEnv.defLib.hashFactors)
		window.aisEnv.defLib.hashFactors(defLib["Tec_TrainingSpeed2"]);

		defLib["Tec_TrainingSpeed3"]={
			codeName:"Tec_TrainingSpeed3",name:"",desc:"",
			icon:"",durTime:86400000,
			cost:{cash:0,gem:0,storage:[]},
			shareName:"Tec_TrainingSpeed3",type:"BldBoost",
			factors:[
				{scope:"Building",name:"MFCSpeed",mbf:4},
			]
		};
		if(window.aisEnv.defLib.hashFactors)
		window.aisEnv.defLib.hashFactors(defLib["Tec_TrainingSpeed3"]);

		window.aisEnv.defLib.clan={
		 inited:1,signinPoints:1,
		 genDonate:{times:1,exp:10,cost:{gem:0,storage:[{store:"Gold",type:"ResGold",num:500000},{store:"Oil",type:"ResOil",num:500000}]}},
		 powerDonate:{exp:30,cost:{gem:50,storage:[{store:"Gold",type:"ResGold",num:500000},{store:"Oil",type:"ResOil",num:500000}]}},
		 levels:[
		  {level:1,exp:0,addMen:0,unlockTec:[],tec:[]},
		  {level:2,exp:1,addMen:2,unlockTec:[{codeName:"Tec_TrainingSpeed",level:1},],tec:[{codeName:"Tec_TrainingSpeed",level:1},]},
		  {level:3,exp:1,addMen:4,unlockTec:[],tec:[{codeName:"Tec_TrainingSpeed",level:1},]},
		  {level:4,exp:1,addMen:6,unlockTec:[{codeName:"Tec_TownHallHP",level:1},],tec:[{codeName:"Tec_TrainingSpeed",level:1},{codeName:"Tec_TownHallHP",level:1},]},
		  {level:5,exp:1,addMen:8,unlockTec:[],tec:[{codeName:"Tec_TrainingSpeed",level:1},{codeName:"Tec_TownHallHP",level:1},]},
		  {level:6,exp:1,addMen:10,unlockTec:[{codeName:"Tec_ResourceMax",level:1},],tec:[{codeName:"Tec_TrainingSpeed",level:1},{codeName:"Tec_TownHallHP",level:1},{codeName:"Tec_ResourceMax",level:1},]},
		  {level:7,exp:1,addMen:12,unlockTec:[],tec:[{codeName:"Tec_TrainingSpeed",level:1},{codeName:"Tec_TownHallHP",level:1},{codeName:"Tec_ResourceMax",level:1},]},
		  {level:8,exp:3500,addMen:14,unlockTec:[{codeName:"Tec_TrapUp",level:1},],tec:[{codeName:"Tec_TrainingSpeed",level:1},{codeName:"Tec_TownHallHP",level:1},{codeName:"Tec_ResourceMax",level:1},{codeName:"Tec_TrapUp",level:1},]},
		  {level:9,exp:4300,addMen:16,unlockTec:[],tec:[{codeName:"Tec_TrainingSpeed",level:1},{codeName:"Tec_TownHallHP",level:1},{codeName:"Tec_ResourceMax",level:1},{codeName:"Tec_TrapUp",level:1},]},
		  {level:10,exp:5100,addMen:18,unlockTec:[{codeName:"Tec_DefenseUp",level:1},],tec:[{codeName:"Tec_TrainingSpeed",level:1},{codeName:"Tec_TownHallHP",level:1},{codeName:"Tec_ResourceMax",level:1},{codeName:"Tec_TrapUp",level:1},{codeName:"Tec_DefenseUp",level:1},]},
		  {level:11,exp:6000,addMen:20,unlockTec:[],tec:[{codeName:"Tec_TrainingSpeed",level:1},{codeName:"Tec_TownHallHP",level:1},{codeName:"Tec_ResourceMax",level:1},{codeName:"Tec_TrapUp",level:1},{codeName:"Tec_DefenseUp",level:1},]},
		  {level:12,exp:7000,addMen:22,unlockTec:[{codeName:"Tec_TrainingSpeed",level:2},],tec:[{codeName:"Tec_TrainingSpeed",level:2},{codeName:"Tec_TownHallHP",level:1},{codeName:"Tec_ResourceMax",level:1},{codeName:"Tec_TrapUp",level:1},{codeName:"Tec_DefenseUp",level:1},]},
		  {level:13,exp:8000,addMen:24,unlockTec:[],tec:[{codeName:"Tec_TrainingSpeed",level:2},{codeName:"Tec_TownHallHP",level:1},{codeName:"Tec_ResourceMax",level:1},{codeName:"Tec_TrapUp",level:1},{codeName:"Tec_DefenseUp",level:1},]},
		  {level:14,exp:9000,addMen:26,unlockTec:[{codeName:"Tec_TownHallHP",level:2},],tec:[{codeName:"Tec_TrainingSpeed",level:2},{codeName:"Tec_TownHallHP",level:2},{codeName:"Tec_ResourceMax",level:1},{codeName:"Tec_TrapUp",level:1},{codeName:"Tec_DefenseUp",level:1},]},
		  {level:15,exp:10000,addMen:28,unlockTec:[],tec:[{codeName:"Tec_TrainingSpeed",level:2},{codeName:"Tec_TownHallHP",level:2},{codeName:"Tec_ResourceMax",level:1},{codeName:"Tec_TrapUp",level:1},{codeName:"Tec_DefenseUp",level:1},]},
		  {level:16,exp:12000,addMen:30,unlockTec:[{codeName:"Tec_ResourceMax",level:2},],tec:[{codeName:"Tec_TrainingSpeed",level:2},{codeName:"Tec_TownHallHP",level:2},{codeName:"Tec_ResourceMax",level:2},{codeName:"Tec_TrapUp",level:1},{codeName:"Tec_DefenseUp",level:1},]},
		  {level:17,exp:14100,addMen:32,unlockTec:[],tec:[{codeName:"Tec_TrainingSpeed",level:2},{codeName:"Tec_TownHallHP",level:2},{codeName:"Tec_ResourceMax",level:2},{codeName:"Tec_TrapUp",level:1},{codeName:"Tec_DefenseUp",level:1},]},
		  {level:18,exp:16200,addMen:34,unlockTec:[{codeName:"Tec_TrapUp",level:2},],tec:[{codeName:"Tec_TrainingSpeed",level:2},{codeName:"Tec_TownHallHP",level:2},{codeName:"Tec_ResourceMax",level:2},{codeName:"Tec_TrapUp",level:2},{codeName:"Tec_DefenseUp",level:1},]},
		  {level:19,exp:18500,addMen:36,unlockTec:[],tec:[{codeName:"Tec_TrainingSpeed",level:2},{codeName:"Tec_TownHallHP",level:2},{codeName:"Tec_ResourceMax",level:2},{codeName:"Tec_TrapUp",level:2},{codeName:"Tec_DefenseUp",level:1},]},
		  {level:20,exp:20800,addMen:38,unlockTec:[{codeName:"Tec_DefenseUp",level:2},],tec:[{codeName:"Tec_TrainingSpeed",level:2},{codeName:"Tec_TownHallHP",level:2},{codeName:"Tec_ResourceMax",level:2},{codeName:"Tec_TrapUp",level:2},{codeName:"Tec_DefenseUp",level:2},]},
		  {level:21,exp:23200,addMen:40,unlockTec:[],tec:[{codeName:"Tec_TrainingSpeed",level:2},{codeName:"Tec_TownHallHP",level:2},{codeName:"Tec_ResourceMax",level:2},{codeName:"Tec_TrapUp",level:2},{codeName:"Tec_DefenseUp",level:2},]},
		  {level:22,exp:25700,addMen:42,unlockTec:[{codeName:"Tec_TrainingSpeed",level:3},],tec:[{codeName:"Tec_TrainingSpeed",level:3},{codeName:"Tec_TownHallHP",level:2},{codeName:"Tec_ResourceMax",level:2},{codeName:"Tec_TrapUp",level:2},{codeName:"Tec_DefenseUp",level:2},]},
		  {level:23,exp:28300,addMen:44,unlockTec:[],tec:[{codeName:"Tec_TrainingSpeed",level:3},{codeName:"Tec_TownHallHP",level:2},{codeName:"Tec_ResourceMax",level:2},{codeName:"Tec_TrapUp",level:2},{codeName:"Tec_DefenseUp",level:2},]},
		  {level:24,exp:31000,addMen:46,unlockTec:[{codeName:"Tec_TownHallHP",level:3},],tec:[{codeName:"Tec_TrainingSpeed",level:3},{codeName:"Tec_TownHallHP",level:3},{codeName:"Tec_ResourceMax",level:2},{codeName:"Tec_TrapUp",level:2},{codeName:"Tec_DefenseUp",level:2},]},
		  {level:25,exp:33800,addMen:48,unlockTec:[],tec:[{codeName:"Tec_TrainingSpeed",level:3},{codeName:"Tec_TownHallHP",level:3},{codeName:"Tec_ResourceMax",level:2},{codeName:"Tec_TrapUp",level:2},{codeName:"Tec_DefenseUp",level:2},]},
		  {level:26,exp:36700,addMen:50,unlockTec:[{codeName:"Tec_ResourceMax",level:3},],tec:[{codeName:"Tec_TrainingSpeed",level:3},{codeName:"Tec_TownHallHP",level:3},{codeName:"Tec_ResourceMax",level:3},{codeName:"Tec_TrapUp",level:2},{codeName:"Tec_DefenseUp",level:2},]},
		  {level:27,exp:36700,addMen:52,unlockTec:[],tec:[{codeName:"Tec_TrainingSpeed",level:3},{codeName:"Tec_TownHallHP",level:3},{codeName:"Tec_ResourceMax",level:3},{codeName:"Tec_TrapUp",level:2},{codeName:"Tec_DefenseUp",level:2},]},
		  {level:28,exp:36700,addMen:54,unlockTec:[],tec:[{codeName:"Tec_TrainingSpeed",level:3},{codeName:"Tec_TownHallHP",level:3},{codeName:"Tec_ResourceMax",level:3},{codeName:"Tec_TrapUp",level:2},{codeName:"Tec_DefenseUp",level:2},]},
		  {level:29,exp:36700,addMen:56,unlockTec:[],tec:[{codeName:"Tec_TrainingSpeed",level:3},{codeName:"Tec_TownHallHP",level:3},{codeName:"Tec_ResourceMax",level:3},{codeName:"Tec_TrapUp",level:2},{codeName:"Tec_DefenseUp",level:2},]},
		  {level:30,exp:36700,addMen:58,unlockTec:[],tec:[{codeName:"Tec_TrainingSpeed",level:3},{codeName:"Tec_TownHallHP",level:3},{codeName:"Tec_ResourceMax",level:3},{codeName:"Tec_TrapUp",level:2},{codeName:"Tec_DefenseUp",level:2},]},
		  {level:31,exp:36700,addMen:60,unlockTec:[],tec:[{codeName:"Tec_TrainingSpeed",level:3},{codeName:"Tec_TownHallHP",level:3},{codeName:"Tec_ResourceMax",level:3},{codeName:"Tec_TrapUp",level:2},{codeName:"Tec_DefenseUp",level:2},]},
		]};
	})();
}
