if(window.aisEnv.textLib)
{
	(function()
	{
		var textLib=window.aisEnv.textLib;
		textLib.npcsName={
			TutorialNPC:"Revenge",
			TutorialNPC2:"The Trap",
			NPC1:"A Waste Outpost",
			NPC2:"Brave's Trip",
			NPC3:"Small Puzzle",
			NPC4:"Beware of Cannon",
			NPC5:"Fort with Cannons",
			NPC6:"Moneygrubber",
			NPC7:"Impregnable Fort",
			NPC8:"Lost in Forest",
			NPC9:"Smash",
			NPC10:"Have a Big Fight",
			NPC11:"Anti-missile",
			NPC12:"Bomb Expert",
			NPC13:"Indestructible Target",
			NPC14:"Warp Fortress",
			NPC15:"Recon Mission",
			NPC16:"A Clever Fool",
			NPC17:"Violent Block",
			NPC18:"Skywalk",
			NPC19:"Green Threat",
			NPC20:"Fort Defense",
			NPC21:"City of Sadness",
			NPC22:"Serene Sea",
			NPC23:"As Strong as Iron",
			NPC24:"The Best Defense",
			NPC25:"Retro Tower",
			NPC26:"A Spooked Bird",
			NPC27:"Bloody Romance",
			NPC28:"Natural Barrier",
			NPC29:"Sieges",
			NPC30:"Your Highness",
			NPC31:"Hard Candy",
			NPC32:"Ambush",
			NPC33:"Impeccable Defense",
			NPC34:"Interstellar Invader",
			NPC35:"Forest Trail",
			NPC36:"Don't Panic",
			NPC37:"Tricks",
			NPC38:"Extra Attack",
			NPC39:"Watch Out",
			NPC40:"Mysterious Maze",
			NPC41:"Fatal Threat",
			NPC42:"Grim Situation",
			NPC43:"Double Team",
			NPC44:"Wedge Shaped Emblem",
			NPC45:"Chaos Theory",
			NPC46:"Harmonious City",
			NPC47:"Vs. KK",
			NPC48:"The Abyss",
		};
	})();
}
