if(window.aisEnv.textLib)
{
	(function()
	{
		var textLib=window.aisEnv.textLib;
		textLib.npcsName={
			TutorialNPC:"반환 요구",
			TutorialNPC2:"퍼즐",
			NPC1:"풋내기",
			NPC2:"승승장구",
			NPC3:"고생길",
			NPC4:"질주 거포",
			NPC5:"담뱃대",
			NPC6:"첫번째 수확",
			NPC7:"현명한 수비",
			NPC8:"우회 전진",
			NPC9:"비우기!",
			NPC10:"엄청난 마을",
			NPC11:"폭격 폭탄투하정",
			NPC12:"폭파전문가",
			NPC13:"요지부동",
			NPC14:"손잡이 보루",
			NPC15:"정찰보초",
			NPC16:"바보",
			NPC17:"13번가 구역",
			NPC18:"하늘회랑",
			NPC19:"비취의 위협",
			NPC20:"마을 수비전",
			NPC21:"애늙은이",
			NPC22:"평온의 바다",
			NPC23:"철옹성",
			NPC24:"삼각방어선",
			NPC25:"로켓의 탑",
			NPC26:"새가슴/화살에 놀란 새",
			NPC27:"핏빛 낭만",
			NPC28:"천연장벽",
			NPC29:"둘러싸기진법",
			NPC30:"금빛영예",
			NPC31:"달콤한 유혹",
			NPC32:"사면초가",
			NPC33:"사면방어",
			NPC34:"우주침략자",
			NPC35:"가로수길",
			NPC36:"공병의 악몽",
			NPC37:"버섯방어",
			NPC38:"격산타우 권법",
			NPC39:"일부러 놓아주기",
			NPC40:"미궁",
			NPC41:"차가운 살기",
			NPC42:"도처의 살기",
			NPC43:"좌우 협공",
			NPC44:"쐐기문장",
			NPC45:"혼돈이론",
			NPC46:"조화의 성",
			NPC47:"패왕기갑장",
			NPC48:"심연의 근거지",
		};
	})();
}
