if(window.aisEnv.textLib)
{
	(function()
	{
		var textLib=window.aisEnv.textLib;
		textLib.bldName={
			Camp:"Parade Ground",
			Camp_Lv1:"Parade Ground Lv.1",
			Camp_Lv2:"Parade Ground Lv.2",
			Camp_Lv3:"Parade Ground Lv.3",
			Camp_Lv4:"Parade Ground Lv.4",
			Camp_Lv5:"Parade Ground Lv.5",
			Camp_Lv6:"Parade Ground Lv.6",
			Camp_Lv7:"Parade Ground Lv.7",
			TownHall:"HQ",
			TownHall_Lv1:"HQ Lv.1",
			TownHall_Lv2:"HQ Lv.2",
			TownHall_Lv3:"HQ Lv.3",
			TownHall_Lv4:"HQ Lv.4",
			TownHall_Lv5:"HQ Lv.5",
			TownHall_Lv6:"HQ Lv.6",
			TownHall_Lv7:"HQ Lv.7",
			TownHall_Lv8:"HQ Lv.8",
			TownHall_Lv9:"HQ Lv.9",
			OilWell:"Energy Driller",
			OilWell_Lv1:"Energy Driller Lv.1",
			OilWell_Lv2:"Energy Driller Lv.2",
			OilWell_Lv3:"Energy Driller Lv.3",
			OilWell_Lv4:"Energy Driller Lv.4",
			OilWell_Lv5:"Energy Driller Lv.5",
			OilWell_Lv6:"Energy Driller Lv.6",
			OilWell_Lv7:"Energy Driller Lv.7",
			OilWell_Lv8:"Energy Driller Lv.8",
			OilWell_Lv9:"Energy Driller Lv.9",
			OilWell_Lv10:"Energy Driller Lv.10",
			OilWell_Lv11:"Energy Driller Lv.11",
			OilTank:"Energy Vat",
			OilTank_Lv1:"Energy Vat Lv.1",
			OilTank_Lv2:"Energy Vat Lv.2",
			OilTank_Lv3:"Energy Vat Lv.3",
			OilTank_Lv4:"Energy Vat Lv.4",
			OilTank_Lv5:"Energy Vat Lv.5",
			OilTank_Lv6:"Energy Vat Lv.6",
			OilTank_Lv7:"Energy Vat Lv.7",
			OilTank_Lv8:"Energy Vat Lv.8",
			OilTank_Lv9:"Energy Vat Lv.9",
			OilTank_Lv10:"Energy Vat Lv.10",
			OilTank_Lv11:"Energy Vat Lv.11",
			GoldMine:"Gold Mine",
			GoldMine_Lv1:"Gold Mine Lv.1",
			GoldMine_Lv2:"Gold Mine Lv.2",
			GoldMine_Lv3:"Gold Mine Lv.3",
			GoldMine_Lv4:"Gold Mine Lv.4",
			GoldMine_Lv5:"Gold Mine Lv.5",
			GoldMine_Lv6:"Gold Mine Lv.6",
			GoldMine_Lv7:"Gold Mine Lv.7",
			GoldMine_Lv8:"Gold Mine Lv.8",
			GoldMine_Lv9:"Gold Mine Lv.9",
			GoldMine_Lv10:"Gold Mine Lv.10",
			GoldMine_Lv11:"Gold Mine Lv.11",
			GoldVault:"Gold Storage",
			GoldVault_Lv1:"Gold Storage Lv.1",
			GoldVault_Lv2:"Gold Storage Lv.2",
			GoldVault_Lv3:"Gold Storage Lv.3",
			GoldVault_Lv4:"Gold Storage Lv.4",
			GoldVault_Lv5:"Gold Storage Lv.5",
			GoldVault_Lv6:"Gold Storage Lv.6",
			GoldVault_Lv7:"Gold Storage Lv.7",
			GoldVault_Lv8:"Gold Storage Lv.8",
			GoldVault_Lv9:"Gold Storage Lv.9",
			GoldVault_Lv10:"Gold Storage Lv.10",
			GoldVault_Lv11:"Gold Storage Lv.11",
			Barrack:"Barracks",
			Barrack_Lv1:"Barracks Lv.1",
			Barrack_Lv2:"Barracks Lv.2",
			Barrack_Lv3:"Barracks Lv.3",
			Barrack_Lv4:"Barracks Lv.4",
			Barrack_Lv5:"Barracks Lv.5",
			Barrack_Lv6:"Barracks Lv.6",
			Barrack_Lv7:"Barracks Lv.7",
			Barrack_Lv8:"Barracks Lv.8",
			Barrack_Lv9:"Barracks Lv.9",
			Barrack_Lv10:"Barracks Lv.10",
			TechLab:"R&D Center",
			TechLab_Lv1:"R&D Center Lv.1",
			TechLab_Lv2:"R&D Center Lv.2",
			TechLab_Lv3:"R&D Center Lv.3",
			TechLab_Lv4:"R&D Center Lv.4",
			TechLab_Lv5:"R&D Center Lv.5",
			TechLab_Lv6:"R&D Center Lv.6",
			Cannon:"Barbette",
			Cannon_Lv1:"Barbette Lv.1",
			Cannon_Lv2:"Barbette Lv.2",
			Cannon_Lv3:"Barbette Lv.3",
			Cannon_Lv4:"Barbette Lv.4",
			Cannon_Lv5:"Barbette Lv.5",
			Cannon_Lv6:"Barbette Lv.6",
			Cannon_Lv7:"Barbette Lv.7",
			Cannon_Lv8:"Barbette Lv.8",
			Cannon_Lv9:"Barbette Lv.9",
			Cannon_Lv10:"Barbette Lv.10",
			Cannon_Lv11:"Barbette Lv.11",
			Tower:"Gunner Tower",
			Tower_Lv1:"Gunner Tower Lv.1",
			Tower_Lv2:"Gunner Tower Lv.2",
			Tower_Lv3:"Gunner Tower Lv.3",
			Tower_Lv4:"Gunner Tower Lv.4",
			Tower_Lv5:"Gunner Tower Lv.5",
			Tower_Lv6:"Gunner Tower Lv.6",
			Tower_Lv7:"Gunner Tower Lv.7",
			Tower_Lv8:"Gunner Tower Lv.8",
			Tower_Lv9:"Gunner Tower Lv.9",
			Tower_Lv10:"Gunner Tower Lv.10",
			Wall:"Wall",
			Wall_Lv1:"Wall Lv.1",
			Wall_Lv2:"Wall Lv.2",
			Wall_Lv3:"Wall Lv.3",
			Wall_Lv4:"Wall Lv.4",
			Wall_Lv5:"Wall Lv.5",
			Wall_Lv6:"Wall Lv.6",
			Wall_Lv7:"Wall Lv.7",
			Wall_Lv8:"Wall Lv.8",
			RocketTower:"Missile Battery",
			RocketTower_Lv1:"Missile Battery Lv.1",
			RocketTower_Lv2:"Missile Battery Lv.2",
			RocketTower_Lv3:"Missile Battery Lv.3",
			RocketTower_Lv4:"Missile Battery Lv.4",
			RocketTower_Lv5:"Missile Battery Lv.5",
			RocketTower_Lv6:"Missile Battery Lv.6",
			RocketTower_Lv7:"Missile Battery Lv.7",
			AATower:"Rocket Launcher",
			AATower_Lv1:"Rocket Launcher Lv.1",
			AATower_Lv2:"Rocket Launcher Lv.2",
			AATower_Lv3:"Rocket Launcher Lv.3",
			AATower_Lv4:"Rocket Launcher Lv.4",
			AATower_Lv5:"Rocket Launcher Lv.5",
			AATower_Lv6:"Rocket Launcher Lv.6",
			Motar:"Missile Silo",
			Motar_Lv1:"Missile Silo Lv.1",
			Motar_Lv2:"Missile Silo Lv.2",
			Motar_Lv3:"Missile Silo Lv.3",
			Motar_Lv4:"Missile Silo Lv.4",
			Motar_Lv5:"Missile Silo Lv.5",
			Motar_Lv6:"Missile Silo Lv.6",
			Motar_Lv7:"Missile Silo Lv.7",
			ClanBld:"Alliance",
			ClanBld_Lv1:"Alliance Lv.1",
			ClanBld_Lv2:"Alliance Lv.2",
			ClanBld_Lv3:"Alliance Lv.3",
			ClanBld_Lv4:"Alliance Lv.4",
			WorkerHut:"EWS",
			WorkerHut_Lv1:"EWS",
			CommunicationsMast:"Enemy's Fort",
			LaserTower:"Prism Tower",
			LaserTower_Lv1:"Prism Tower Lv.1",
			LaserTower_Lv2:"Prism Tower Lv.2",
			LaserTower_Lv3:"Prism Tower Lv.3",
			LaserTower_Lv4:"Prism Tower Lv.4",
			LaserTower_Lv5:"Prism Tower Lv.5",
			LaserTower_Lv6:"Prism Tower Lv.6",
			SpellLab:"Satellite Station",
			SpellLab_Lv1:"Satellite Station Lv.1",
			SpellLab_Lv2:"Satellite Station Lv.2",
			SpellLab_Lv3:"Satellite Station Lv.3",
			SpellLab_Lv4:"Satellite Station Lv.4",
			RGunTower:"Mega Laser",
			RGunTower_Lv1:"Mega Laser Lv.1",
			DiamondMine:"Faceting Machine",
			DiamondMine_Lv1:"Faceting Machine",
			Mine:"Bomb",
			Ejector:"Mine Trap",
			Superbomb:"Super Bomb",
			Halloweenbomb:"Trick or Treat",
			Conifers:"Flowers",
			Megalithic:"Stone",
			SmallStone:"Stone",
			Bush:"Shrub",
			Tree:"Tree",
			Trunk:"Trunk",
			Mushrooms:"Flowers",
			Grave:"Gravestone",
			RoundTree:"Tree",
			Pillars:"Stone",
			Kistler:"Stone",
			Xmastree:"X'mas Tree",
			BarbarianStatue:"Large Granite Statue",
			Torch:"Large Silver Statue",
			GoblinPole:"Large Gold Statue",
			WhiteFlag:"White Windmill",
			SkullFlag:"Green Windmill",
			Flowerbox1:"Peonies",
			Flowerbox2:"Bluebells",
			Windmeter:"Red Windmill",
			DownArrowFlag:"Granite Hero Statue",
			UpArrowFlag:"Silver Hero Statue",
			SkullAltar:"Gold Hero Statue",
			USAFlag:"National Flag",
			CanadaFlag:"National Flag",
			ItaliaFlag:"National Flag",
			GermanyFlag:"National Flag",
			FinlandFlag:"National Flag",
			SpainFlag:"National Flag",
			FranceFlag:"National Flag",
			GBRFlag:"National Flag",
			BrazilFlag:"National Flag",
			SwedenFlag:"National Flag",
			ChinaFlag:"National Flag",
			NorwayFlag:"National Flag",
			ThailandFlag:"National Flag",
			IndiaFlag:"National Flag",
			AustraliaFlag:"National Flag",
			SouthKoreaFlag:"National Flag",
			JapanFlag:"National Flag",
			TurkeyFlag:"National Flag",
			IndonesiaFlag:"National Flag",
			NetherlandsFlag:"National Flag",
			PhilippinesFlag:"National Flag",
			SingaporeFlag:"National Flag",
			PEKKAStatue:"Statue of KK",
		};
		textLib.bldInfo={
			Camp:"After training, your troops will be at the Parade Ground waiting for orders. \r\nBuild more Parade Ground and upgrade them to assemble a formidable army.",
			TownHall:"Headquarters (HQ) is the core of your fort. \r\nTo fortify your territory, you need to upgrade your HQ. \r\nWith the development of HQ, more types of buildings and troops will be unlocked.",
			OilWell:"Energy is extracted from underground. \r\nEnergy is essential for military activities and troops training. \r\nUpgrading constructions also consumes energy. \r\nUpgrade your Energy Driller to expand energy production and put it to good use.",
			OilTank:"Energy is stored in Energy Vat. \r\n\r\nUpgrade the vats to increase their capacity. \r\n\r\nBeware of enemy snappers who may deplete your energy.",
			GoldMine:"Gold is another important resource. \r\nBoost its production with Gems when your Gold Mine has reached level 4. \r\n\r\nYou can also loot from enemy forts.",
			GoldVault:"Looters are always targeting your gold. \r\n\r\nUpgrade your storages to increase their capacity and durability in battle.",
			Barrack:"Recruit and train your troops in the Barracks. \r\nSelect proper troops to raid an enemy fort. \r\nA powerful helper will make the fight easier. \r\n\r\nTraining does take a bit of time so use Gems to speed up the process.",
			TechLab:"We have hired many scientists to conduct research in the R&D Center. We have no idea about their research but know that their work will result in big leaps in our military capabilities. \r\n\r\nBe patient and give the scientists some time. They will not let you down.",
			Cannon:"Build Barbette to protect your resources and upgrade it to increase its firepower. \r\nYou need to pay attention as it does not work while being upgraded.",
			Tower:"Gunner Tower offers an extended shooting range for your defence. \r\n\r\nGunners can also attack enemies in the sky.",
			Wall:"Walls are the shield protecting your buildings and double as an obstacle to slow enemy movements. \r\n\r\n You still need to pay attention to the troops in the sky.",
			RocketTower:"Missile Battery consumes large resources, but is more powerful to defend against the enemy on the ground or in the sky. \r\n\r\nTrust me, it is really worth the cost!",
			AATower:"Rocket is the perfect weapon to deal with all flying troops, but it cannot kill anyone on the ground. \r\n\r\nThat is to say, position it strategically.",
			Motar:"Missile Battery fires rallying enemies with shells. \r\n\r\nPlease do not let the enemies too close to it as the weapon can only hit the enemies afar.",
			ClanBld:"Reinforcement troops from your allies are stationed here to help you in battle. \r\nSend troops to help your friends and you will get extra EXP in return.",
			WorkerHut:"Your fort is built by workers from Engineering Work Station (EWS). \r\n\r\nOnly idle workers can be assigned for a new project so you may consider building another EWS with Gems to expedite the development of your fort.",
			LaserTower:"Prism Tower is our secret weapon. Prism refracts incoming light which produces a shield to hide it from view. \r\nThe tower will fire upon enemies when they approach.",
			SpellLab:"Satellite Station is where we can communicate with aliens. \r\nLearning ET skills or asking our alien friends for help will give us a chance to tip the balance in battle.",
			RGunTower:"Mega gun, with terribly fast shooting speed and amazing attack power, shoots laser to inflict damage to enemies. This weapon is an enemy's worst nightmare.",
			DiamondMine:"With the Faceting Machine, you can cut and polish raw gemstones in your fort. \r\n It takes 24 hours to cut 1 Gem which you can use to speed up processes or purchase buildings. The Gem in machine cannot be looted by other players. \r\nPlease collect your Gems in time.",
			Mine:"This explosive device is normally concealed in the ground to inflict unexpected damage on its target.",
			Ejector:"Mine Trap absorbs electricity in the air and creates electrical energy to zap those sneaky visitors.",
			Superbomb:"The Super Bomb is the gift we prepared for our most loved enemy!",
			Halloweenbomb:"Trick or Treat. Why not prepare an unpleasant surprise for the invaders! Bomb the enemy to pieces with dynamite will be the best way to celebrate Halloween.",
			favor_any:"All",
			favor_res:"Resources",
			favor_def:"Defenses",
			favor_wall:"Walls",
			target_gnd:"Ground",
			target_air:"Air",
			target_all:"Ground & Air",
			dmgtype_aoe:"Area Splash",
			dmgtype_single:"Single Target",
		};
	})();
}
