if(window.aisEnv.textLib)
{
	(function()
	{
		var textLib=window.aisEnv.textLib;
		textLib.vipPrivilegeName={
		};
		textLib.vipPrivilegeInfo={
			vipWallNum:"",
			vipMineNum:"",
			vipEjectorNum:"",
			vipSuperbombNum:"",
			vipResCrit:"",
			vipBattleWaitTime:"",
			vipLimitedSalesGold:"",
			vipLimitedSalesElixir:"",
			vipRequestUnitsWaitTime:"",
			vipTrainTimeDiscount:"",
			vipBLDTimeDiscount:"",
			vipDiamonBoost:"",
		};
	})();
}
