if(window.aisEnv.textLib)
{
	(function()
	{
		var textLib=window.aisEnv.textLib;
		textLib.bldName={
			Camp:"훈련장",
			Camp_Lv1:"훈련장 1레벨",
			Camp_Lv2:"훈련장 2레벨",
			Camp_Lv3:"훈련장 3레벨",
			Camp_Lv4:"훈련장 4레벨",
			Camp_Lv5:"훈련장 5레벨",
			Camp_Lv6:"훈련장 6레벨",
			Camp_Lv7:"훈련장 7레벨",
			TownHall:"지휘센터",
			TownHall_Lv1:"지휘센터 1레벨",
			TownHall_Lv2:"지휘센터 2레벨",
			TownHall_Lv3:"지휘센터 3레벨",
			TownHall_Lv4:"지휘센터 4레벨",
			TownHall_Lv5:"지휘센터 5레벨",
			TownHall_Lv6:"지휘센터 6레벨",
			TownHall_Lv7:"지휘센터 7레벨",
			TownHall_Lv8:"지휘센터 8레벨",
			TownHall_Lv9:"지휘센터 9레벨",
			OilWell:"에너지 탐사정",
			OilWell_Lv1:"에너지 탐사정 1레벨",
			OilWell_Lv2:"에너지 탐사정 2레벨",
			OilWell_Lv3:"에너지 탐사정 3레벨",
			OilWell_Lv4:"에너지 탐사정 4레벨",
			OilWell_Lv5:"에너지 탐사정 5레벨",
			OilWell_Lv6:"에너지 탐사정 6레벨",
			OilWell_Lv7:"에너지 탐사정 7레벨",
			OilWell_Lv8:"에너지 탐사정 8레벨",
			OilWell_Lv9:"에너지 탐사정 9레벨",
			OilWell_Lv10:"에너지 탐사정 10레벨",
			OilWell_Lv11:"에너지 탐사정 11레벨",
			OilTank:"에너지 탱크",
			OilTank_Lv1:"에너지 탱크 1레벨",
			OilTank_Lv2:"에너지 탱크 2레벨",
			OilTank_Lv3:"에너지 탱크 3레벨",
			OilTank_Lv4:"에너지 탱크 4레벨",
			OilTank_Lv5:"에너지 탱크 5레벨",
			OilTank_Lv6:"에너지 탱크 6레벨",
			OilTank_Lv7:"에너지 탱크 7레벨",
			OilTank_Lv8:"에너지 탱크 8레벨",
			OilTank_Lv9:"에너지 탱크 9레벨",
			OilTank_Lv10:"에너지 탱크 10레벨",
			OilTank_Lv11:"에너지 탱크 11레벨",
			GoldMine:"금광",
			GoldMine_Lv1:"금광 1레벨",
			GoldMine_Lv2:"금광 2레벨",
			GoldMine_Lv3:"금광 3레벨",
			GoldMine_Lv4:"금광 4레벨",
			GoldMine_Lv5:"금광 5레벨",
			GoldMine_Lv6:"금광 6레벨",
			GoldMine_Lv7:"금광 7레벨",
			GoldMine_Lv8:"금광 8레벨",
			GoldMine_Lv9:"금광 9레벨",
			GoldMine_Lv10:"금광 10레벨",
			GoldMine_Lv11:"금광 11레벨",
			GoldVault:"금고",
			GoldVault_Lv1:"금고 1레벨",
			GoldVault_Lv2:"금고 2레벨",
			GoldVault_Lv3:"금고 3레벨",
			GoldVault_Lv4:"금고 4레벨",
			GoldVault_Lv5:"금고 5레벨",
			GoldVault_Lv6:"금고 6레벨",
			GoldVault_Lv7:"금고 7레벨",
			GoldVault_Lv8:"금고 8레벨",
			GoldVault_Lv9:"금고 9레벨",
			GoldVault_Lv10:"금고 10레벨",
			GoldVault_Lv11:"금고 11레벨",
			Barrack:"병영",
			Barrack_Lv1:"병영 1레벨",
			Barrack_Lv2:"병영 2레벨",
			Barrack_Lv3:"병영 3레벨",
			Barrack_Lv4:"병영 4레벨",
			Barrack_Lv5:"병영 5레벨",
			Barrack_Lv6:"병영 6레벨",
			Barrack_Lv7:"병영 7레벨",
			Barrack_Lv8:"병영 8레벨",
			Barrack_Lv9:"병영 9레벨",
			Barrack_Lv10:"병영 10레벨",
			TechLab:"연구소",
			TechLab_Lv1:"연구소 1레벨",
			TechLab_Lv2:"연구소 2레벨",
			TechLab_Lv3:"연구소 3레벨",
			TechLab_Lv4:"연구소 4레벨",
			TechLab_Lv5:"연구소 5레벨",
			TechLab_Lv6:"연구소 6레벨",
			Cannon:"자동대포",
			Cannon_Lv1:"자동대포 1레벨",
			Cannon_Lv2:"자동대포 2레벨",
			Cannon_Lv3:"자동대포 3레벨",
			Cannon_Lv4:"자동대포 4레벨",
			Cannon_Lv5:"자동대포 5레벨",
			Cannon_Lv6:"자동대포 6레벨",
			Cannon_Lv7:"자동대포 7레벨",
			Cannon_Lv8:"자동대포 8레벨",
			Cannon_Lv9:"자동대포 9레벨",
			Cannon_Lv10:"자동대포 10레벨",
			Cannon_Lv11:"자동대포 11레벨",
			Tower:"기관총탑",
			Tower_Lv1:"기관총탑 1레벨",
			Tower_Lv2:"기관총탑 2레벨",
			Tower_Lv3:"기관총탑 3레벨",
			Tower_Lv4:"기관총탑 4레벨",
			Tower_Lv5:"기관총탑 5레벨",
			Tower_Lv6:"기관총탑 6레벨",
			Tower_Lv7:"기관총탑 7레벨",
			Tower_Lv8:"기관총탑 8레벨",
			Tower_Lv9:"기관총탑 9레벨",
			Tower_Lv10:"기관총탑 10레벨",
			Wall:"벽",
			Wall_Lv1:"벽 1레벨",
			Wall_Lv2:"벽 2레벨",
			Wall_Lv3:"벽 3레벨",
			Wall_Lv4:"벽 4레벨",
			Wall_Lv5:"벽 5레벨",
			Wall_Lv6:"벽 6레벨",
			Wall_Lv7:"벽 7레벨",
			Wall_Lv8:"벽 8레벨",
			RocketTower:"로켓탑",
			RocketTower_Lv1:"로켓탑 1레벨",
			RocketTower_Lv2:"로켓탑 2레벨",
			RocketTower_Lv3:"로켓탑 3레벨",
			RocketTower_Lv4:"로켓탑 4레벨",
			RocketTower_Lv5:"로켓탑 5레벨",
			RocketTower_Lv6:"로켓탑 6레벨",
			RocketTower_Lv7:"로켓탑 7레벨",
			AATower:"공중유도탄",
			AATower_Lv1:"공중유도탄 1레벨",
			AATower_Lv2:"공중유도탄 2레벨",
			AATower_Lv3:"공중유도탄 3레벨",
			AATower_Lv4:"공중유도탄 4레벨",
			AATower_Lv5:"공중유도탄 5레벨",
			AATower_Lv6:"공중유도탄 6레벨",
			Motar:"폭탄투하정",
			Motar_Lv1:"폭탄투하정 1레벨",
			Motar_Lv2:"폭탄투하정 2레벨",
			Motar_Lv3:"폭탄투하정 3레벨",
			Motar_Lv4:"폭탄투하정 4레벨",
			Motar_Lv5:"폭탄투하정 5레벨",
			Motar_Lv6:"폭탄투하정 6레벨",
			Motar_Lv7:"폭탄투하정 7레벨",
			ClanBld:"연합군지원소",
			ClanBld_Lv1:"연합군지원소 1레벨",
			ClanBld_Lv2:"연합군지원소 2레벨",
			ClanBld_Lv3:"연합군지원소 3레벨",
			ClanBld_Lv4:"연합군지원소 4레벨",
			WorkerHut:"공사장",
			WorkerHut_Lv1:"공사장 1레벨",
			CommunicationsMast:"적 근거지",
			LaserTower:"투명 에너지탑",
			LaserTower_Lv1:"투명 에너지탑 1레벨",
			LaserTower_Lv2:"투명 에너지탑 2레벨",
			LaserTower_Lv3:"투명 에너지탑 3레벨",
			LaserTower_Lv4:"투명 에너지탑 4레벨",
			LaserTower_Lv5:"투명 에너지탑 5레벨",
			LaserTower_Lv6:"투명 에너지탑 6레벨",
			SpellLab:"위성통신소",
			SpellLab_Lv1:"위성통신소 1레벨",
			SpellLab_Lv2:"위성통신소 2레벨",
			SpellLab_Lv3:"위성통신소 3레벨",
			SpellLab_Lv4:"위성통신소 4레벨",
			RGunTower:"전자포",
			RGunTower_Lv1:"전자포 1레벨",
			DiamondMine:"다이아몬드 용접기",
			DiamondMine_Lv1:"다이아몬드 용접기",
			Mine:"지뢰",
			Ejector:"벼락유도기",
			Superbomb:"수퍼폭탄",
			Halloweenbomb:"할로윈폭탄",
			Conifers:"꽃떨기",
			Megalithic:"돌",
			SmallStone:"돌",
			Bush:"관목",
			Tree:"나무",
			Trunk:"나무줄기",
			Mushrooms:"꽃떨기",
			Grave:"묘비",
			RoundTree:"나무",
			Pillars:"돌",
			Kistler:"돌",
			Xmastree:"크리스마스 트리",
			BarbarianStatue:"결사대 석상",
			Torch:"결사대 은조각상",
			GoblinPole:"결사대 금조각상",
			WhiteFlag:"흰색 풍차",
			SkullFlag:"녹색 풍차",
			Flowerbox1:"빨강 분재",
			Flowerbox2:"파란 분재",
			Windmeter:"빨강 풍차",
			DownArrowFlag:"저격수 석상",
			UpArrowFlag:"저격수 은조각상",
			SkullAltar:"저격수 금조각상",
			USAFlag:"국기",
			CanadaFlag:"국기",
			ItaliaFlag:"국기",
			GermanyFlag:"국기",
			FinlandFlag:"국기",
			SpainFlag:"국기",
			FranceFlag:"국기",
			GBRFlag:"국기",
			BrazilFlag:"국기",
			SwedenFlag:"국기",
			ChinaFlag:"국기",
			NorwayFlag:"국기",
			ThailandFlag:"국기",
			IndiaFlag:"국기",
			AustraliaFlag:"국기",
			SouthKoreaFlag:"국기",
			JapanFlag:"국기",
			TurkeyFlag:"국기",
			IndonesiaFlag:"국기",
			NetherlandsFlag:"국기",
			PhilippinesFlag:"국기",
			SingaporeFlag:"국기",
			PEKKAStatue:"패왕기갑 금조각상",
		};
		textLib.bldInfo={
			Camp:"병영에서 훈련을 완료한 전투부대는 훈련장에 집결합니다.\r\n훈련장 레벨업, 추가 건설을 하면 부대를 많이 집결시켜 전투력을 높입니다.",
			TownHall:"지휘센터는 기지의 핵심건물로 레벨에 따라 현 스테이지에서 건설가능한 건물 종류, 수량, 각 건물의 최고 레벨이 결정됩니다. \r\n지휘센터 레벨을 높여야 새 건물, 높은 레벨의 건물을 활성화할 수 있습니다.\r\n기지의 발전과 지휘센터는 밀접한 관계가 있습니다.",
			OilWell:"에너지 탐사정은 드릴을 사용해 지하 에너지 자원을 채굴할 수 있습니다.\r\n중요한 군사 자원인 에너지는 생산, 훈련, 전투에 사용됩니다. \r\n병종, 건물 레벨업 시 많은 에너지가 소모됩니다.\r\n한정된 에너지로 새 부대 훈련에 우선 사용해 약탈을 시작합니다.",
			OilTank:"에너지 탱크는 에너지 저장 장소로 채굴, 약탈한 에너지는 탱크 안에 저장합니다.\r\n\r\n에터지 탱크 레벨은 저장 가능한 에너지의 최대 수량을 결정합니다.\r\n\r\n큰 손해를 입지 않도록 적의 공병이 에너지 탱크에 접근하는 것을 막아야 합니다.",
			GoldMine:"지하에서 채굴한 황금도 중요한 자원입니다. 금광은 황금 채굴에 좋습니다.\r\n금광이 4레벨이 되면 다이아몬드 사용해 황금 채굴 속도를 높여 짧은 시간에 많은 황금을 획득할 수 있습니다.\r\n\r\n물론 다른 기지의 황금을 약탈하는 것이 가장 효과적인 방법입니다",
			GoldVault:"채굴, 약탈한 황금을 금고에 보관하기 때문에 금고는 최고의 타깃입니다. \r\n\r\n금고를 레벨업해 저장용량과 내구성을 높일 수 있습니다. 금고를 잘 지키세요.",
			Barrack:"병영에서 전투부대를 훈련, 생산할 수 있습니다. 고급 병영은 강력한 부대를 활성화합니다.\r\n고레벨 병종은 전투를 쉽게 만들어 줍니다.\r\n하지만 전략이 있어야 승리할 수 있습니다.\r\n\r\n병영 레벨업 후 다이아몬드 사용해 병영의 훈련, 생산 효율을 높이면 짧은 시간에 많은 전투부대가 새 약탈을 시작할 수 있습니다",
			TechLab:"연구소의 과학자들은 연구를 통해 전투부대와 위성지원의 능력을 향상시킵니다.\r\n\r\n연구에 많은 자원과 시간이 들지만 가치가 있습니다.",
			Cannon:"자동대포는 효과적인 방어건물로 레벨업하면 높은 화력을 방출할 수 있습니다.\r\n주의! 자동대포 레벨업 중에는 공격을 방어할 수 없습니다.",
			Tower:"기관총탑은 대포 장착 고도가 높아 사정거리가 깁니다.\r\n\r\n또한 공중 침입을 방어할 수 있습니다. 자동대포로는 할 수 없습니다.",
			Wall:"장벽은 적의 공격을 지연시킵니다. \r\n\r\n지상부대에만 효과가 있습니다.",
			RocketTower:"로켓탑은 제작단가가 높지만 가치가 있는 강력한 방어건물입니다!\r\n\r\n적이 지상, 공중 어느 곳으로 와도 엄청난 단체 공격 데미지를 줍니다.",
			AATower:"공중유도탄은 공중부대의 천적이지만 지상부대에는 데미지를 줄 수 없습니다.\r\n\r\n적합한 지점에 배칠해 공중부대에 최대 데미지를 주는 것이 올바른 전략입니다.",
			Motar:"폭탄투하정은 대형포탄을 발사해 모여있는 적에게 단체 데미지를 줍니다! \r\n\r\n발사 각도에 제한이 있어 자신 주변은 공격할 수 없으니 적이 접근하지 못하도록 해야 합니다.",
			ClanBld:"연합군지원소에서 연합군과 연락할 수 있습니다. 연합군지원소에서 연합군과\r\n서로 지원할 수 있고 전투 중 추가 전투력을 얻습니다.\r\n\r\n연합군에 지원군을 파견하면 추가 경험치를 획득할 수 있습니다.",
			WorkerHut:"공사장에 휴식중인 건설 일꾼이 있어야 건설, 레벨업을 할 수 있습니다.\r\n\r\n공사장이 많으면 동시에 여러 건설 업무를 진행할 수 있습니다. 다이아몬드를 사용해 많은 공사장을 획득하면 기지 건설과 발전속도를 높일 수 있습니다.",
			LaserTower:"투명 에너지탑이라는 이름처럼 평소에는 투명 상태입니다. \r\n하지만 적이 다가오면 공중 부대든, 지상 부대든 고성능의 레이저빔을 발사해 태워버립니다..",
			SpellLab:"위성통신소는 자원을 소모해 웨이브형태로 하늘의 전투 위성에 에너지를 보충합니다.\r\n위성 준비가 끝나면 전투 중 공중 지원부대를 사용할 수 있습니다.",
			RGunTower:"전자포는 에너지를 사용해 포탄을 보충합니다. 에너지탄은 일반 포탄과 달리 무서운 위력을 지닙다. 빠른 발사속도와 큰 위력으로 지상부대에겐 공포의 대상입니다.",
			DiamondMine:"다이아몬드는 고온고압 무산소의 환경에서 오랜 시간에 걸쳐 아름다운 다이아몬드 결정체를 형성합니다.\r\n다이아몬드 용접기는 24시간마다 다이아몬드 1알을 생산하니 약탈되지 않도록 합니다. \r\n자원을 낭비하지 않도록 제때 수령하세요.",
			Mine:"지뢰는 지상에서 행진하는 부대에 뜻밖의 데미지를 줍니다. 지뢰를 적의 경유지의 묻으면 최대 데미지를 입힐 수 있습니다.",
			Ejector:"벼락유도기는 수신기로 공기 중의 전기를 저장합니다. 적이 지나갈 때 순식간에 저장된 전기에너지를 분출해 적을 즉사시킵니다.",
			Superbomb:"수퍼폭탄은 티끌모아 태산이라고 할 수 있습니다. 대량의 폭약을 쌓으면 무시무시한 데미지를 줍니다.",
			Halloweenbomb:"할로윈데이 전용 폭탄. 할로윈의 즐거움을 선사합니다!",
			favor_any:"전부",
			favor_res:"자원건물",
			favor_def:"방어건물",
			favor_wall:"성벽",
			target_gnd:"지상",
			target_air:"공중",
			target_all:"지상과 공중",
			dmgtype_aoe:"구역에 뿌리기",
			dmgtype_single:"단일 타깃",
		};
	})();
}
