if(window.aisEnv.textLib)
{
	(function()
	{
		var textLib=window.aisEnv.textLib;
		textLib.itemName={
			itm_token_1:"胜利徽章",
			itm_token_2:"五星徽章",
			itm_token_3:"精英徽章",
			itm_token_4:"太阳徽章",
			itm_paper:"机甲图纸",
			itm_gift_1:"测试礼包1",
			itm_gift_2:"测试礼包2",
		};
		textLib.itemInfo={
			itm_token_1:"胜利徽章，可在神秘商店换取礼品",
			itm_token_2:"五星徽章，可在神秘商店换取礼品",
			itm_token_3:"精英徽章，可在神秘商店换取礼品",
			itm_token_4:"太阳徽章，可在神秘商店换取礼品\n不可被掠夺",
			itm_paper:"机甲强化30至35级所需材料。可在神秘商店换取。",
			itm_gift_1:"需要1个胜利徽章开启，超时空补给第一档随机",
			itm_gift_2:"需要1个五星徽章开启，机甲福袋物品",
		};
	})();
}
