if(window.aisEnv.textLib)
{
	(function()
	{
		var textLib=window.aisEnv.textLib;
		textLib.achvmntName={
			bindemail:"绑定邮箱",
			chargemoney:"钻石达人",
			goldstoragelevel:"大富豪",
			npcstars:"剿匪英雄传",
			townhall:"超级要塞",
			clearobstacles:"清洁大队长",
			unitunlock:"NB新事物",
			lootgold:"黄金爱好者",
			lootelixir:"能源搬家公司",
			victorypoints:"崭露头角",
			castlelevel:"攻守同盟",
			destroywalls:"破墙专家",
			destroytownhall:"高价值目标",
			destroybuilder:"延缓工程",
			pvpattacks:"攻无不克",
			pvpdefenses:"坚不可摧",
			donateunits:"仗义没话说",
			destroymotar:"巨炮杀手",
			mechstrengthen:"机甲传奇",
		};
		textLib.achvmntInfo={
			bindemail:"在设置页面的账户管理中，完成账号绑定的操作，便可获得海量资源奖励！",
			chargemoney:"购买任意数量的钻石，即可免费建造一座可以制造钻石的钻石熔压器！",
			goldstoragelevel:"升级金库等级至<number>级。",
			npcstars:"在单人游戏中，累积获得<number>颗星星。",
			townhall:"指挥中心等级提升至<number>级。",
			clearobstacles:"累计清理<number>个在城市内的障碍物（树，石头，灌木等等）。",
			unitunlock:"升级兵营等级至<number>，以解锁新的兵种。",
			lootgold:"累积掠夺<number>的黄金。",
			lootelixir:"累积掠夺<number>的能源。",
			victorypoints:"通过战斗获得的勋章数达到<number>。玩家对战有效。",
			castlelevel:"升级盟军支援站等级至<number>级。",
			destroywalls:"在战斗中累积摧毁<number>个城墙。玩家对战有效。",
			destroytownhall:"在战斗中累积摧毁<number>个的指挥中心。玩家对战有效。",
			destroybuilder:"在战斗中累积摧毁<number>个工程站。玩家对战有效。",
			pvpattacks:"进攻胜利次数累积达到<number>次。玩家对战有效。",
			pvpdefenses:"成功抵御敌人的进攻次数累积达到<number>次。",
			donateunits:"累积捐赠<number>个单位来支援你的盟友。",
			destroymotar:"在战斗中累积摧毁<number>个的投弹井。",
			mechstrengthen:"通过强化，使任意机甲组件提升至<number>级。强化后的机甲在战斗中将更强大！",
		};
	})();
}
