if(window.aisEnv.textLib)
{
	(function()
	{
		var textLib=window.aisEnv.textLib;
		textLib.boxName={
			box1:"特殊补给",
			box2:"高级补给",
			box3:"惊喜圣诞树",
			box4:"神奇宝箱",
			box5:"周年庆蛋糕",
		};
		textLib.boxInfo={
			box1:"超时空物资补给超时空物资补给超时空物资补给",
			box2:"超时空物资补给超时空物资补给超时空物资补给",
			box3:"实在是太棒了，我们发现了一棵惊喜圣诞树！\r\n\r\n使用寻宝功能，将发现隐藏在其中的神秘礼物！",
			box4:"实在是太棒了，我们发现了一个神奇宝箱！\r\n\r\n使用寻宝功能，将发现隐藏在其中的神奇宝物！",
			box5:"实在是太棒了，我们发现了一个周年庆蛋糕！\r\n\r\n使用寻宝功能，将发现隐藏在其中的神奇宝物！",
		};
	})();
}
